import type { AgentState, Config, DispatchRecord, Env, HeartbeatRecord, DurableObjectStubLike, ReserveResult } from './types.ts';
import { CORE_LIMITS } from './config.ts';

export interface GithubConfig { repository:string; workflow:string; ref:string; apiVersion:string; autoDispatch:boolean; enableCancel:boolean; allowedWorkflows:string[]; githubTimeoutMs:number; maxResponseBytes:number; }
export const METRIC_NAMES=['auth_denied','heartbeat_invalid','rate_limit_hit','hb_running','hb_completed','hb_failed','dispatch_ok','dispatch_fail','verify_pass','verify_fail','breaker_trip','limit_hit'] as const;
export class Metrics { private v:Record<string,number>=Object.fromEntries(METRIC_NAMES.map(x=>[x,0])); inc(k:string){const current=this.v[k];if(current===undefined)return;this.v[k]=Math.min(Number.MAX_SAFE_INTEGER,current+1);} snapshot(){return {...this.v};} }
export const DEFAULT_CONFIG:Config={...CORE_LIMITS,rate:{heartbeat:{windowMs:60000,limit:60},mutation:{windowMs:60000,limit:30},failsBump:{windowMs:60000,limit:12},dlog:{windowMs:60000,limit:30},forget:{windowMs:3600000,limit:2}}};
const bool=(v:string|undefined,f:boolean)=>v===undefined?f:['1','true','yes','on'].includes(v.trim().toLowerCase())?true:['0','false','no','off',''].includes(v.trim().toLowerCase())?false:((()=>{throw new Error('INVALID_BOOL')})());
const list=(v:string|undefined,max:number)=>{if(!v)return [];const a=[...new Set(v.split(',').map(x=>x.trim()).filter(Boolean))];if(a.length>max||a.some(x=>!/^[A-Za-z0-9_.:-]+$/u.test(x)))throw new Error('INVALID_AGENTS');return a;};
const repoOk=(x:string)=>/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/u.test(x)&&!x.includes('..');
const flowOk=(x:string,maxBytes=CORE_LIMITS.maxWorkflowBytes)=>new TextEncoder().encode(x).byteLength<=maxBytes&&/^[A-Za-z0-9_./-]+$/u.test(x)&&!x.includes('..')&&!x.startsWith('/')&&!x.endsWith('/');
export function loadConfig(env:Env):{config:Config;agents:string[];github:GithubConfig|null}|null{try{const agents=list(env.WATCHDOG_AGENTS,DEFAULT_CONFIG.maxAgents);const repo=env.GITHUB_REPOSITORY?.trim();const workflow=env.GITHUB_DISPATCH_WORKFLOW?.trim();const ref=env.GITHUB_DISPATCH_REF?.trim()||'execution';const token=env.GITHUB_TOKEN;const present=Boolean(repo||workflow||token);let github:null|GithubConfig=null;if(present){if(!repo||!workflow||!token||!repoOk(repo)||!flowOk(workflow,DEFAULT_CONFIG.maxWorkflowBytes)||!flowOk(ref,DEFAULT_CONFIG.maxWorkflowBytes))throw new Error('INVALID_GITHUB_CONFIG');const apiVersion=env.GITHUB_API_VERSION?.trim()||'2026-03-10';if(!/^\d{4}-\d{2}-\d{2}$/u.test(apiVersion))throw new Error('INVALID_API_VERSION');const autoDispatch=bool(env.WATCHDOG_AUTO_DISPATCH,true);const enableCancel=bool(env.WATCHDOG_ENABLE_HUNG_CANCEL,false);if((autoDispatch||enableCancel)&&agents.length===0)throw new Error('NO_AGENTS');github={repository:repo,workflow,ref,apiVersion,autoDispatch,enableCancel,allowedWorkflows:[workflow],githubTimeoutMs:DEFAULT_CONFIG.githubTimeoutMs,maxResponseBytes:DEFAULT_CONFIG.maxResponseBytes};}return {config:DEFAULT_CONFIG,agents,github};}catch{return null;}}
async function digest(s:string){return new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));}
async function ct(a:string,b:string){const [x,y]=await Promise.all([digest(a),digest(b)]);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=(x[i] ?? 0)^(y[i] ?? 0);return d===0;}
function token(req:Request){const v=req.headers.get('Authorization')?.trim()??'';const m=/^Bearer ([\x21-\x7E]+)$/u.exec(v);return m?.[1]??null;}
export async function authAgent(req:Request,env:Env,metrics:Metrics){const t=token(req);const current=env.AGENT_TOKEN;if(!t||!current){metrics.inc('auth_denied');throw new HttpError(401,'UNAUTHORIZED');}if(!(await ct(t,current))){metrics.inc('auth_denied');throw new HttpError(401,'UNAUTHORIZED');}return await digest(t).then(x=>Array.from(x).map(b=>b.toString(16).padStart(2,'0')).join(''));}
export async function authAdmin(req:Request,env:Env,metrics:Metrics){const t=token(req);if(!t||!env.ADMIN_TOKEN||!(await ct(t,env.ADMIN_TOKEN))){metrics.inc('auth_denied');throw new HttpError(401,'UNAUTHORIZED');}}
export class HttpError extends Error {
  readonly status: number;
  readonly code: string;
  constructor(status: number, code: string) {
    super(code);
    this.status = status;
    this.code = code;
  }
}
export async function readBody(req:Request,max:number){const cl=req.headers.get('Content-Length');if(cl&&Number.isFinite(Number(cl))&&Number(cl)>max)throw new HttpError(413,'BODY_TOO_LARGE');const r=req.body?.getReader();if(!r)return '';const parts:Uint8Array[]=[];let total=0;try{for(;;){const x=await r.read();if(x.done)break;total+=x.value.byteLength;if(total>max){await r.cancel();throw new HttpError(413,'BODY_TOO_LARGE');}parts.push(x.value);}}finally{r.releaseLock();}const out=new Uint8Array(total);let o=0;for(const p of parts){out.set(p,o);o+=p.byteLength;}try{return new TextDecoder('utf-8',{fatal:true}).decode(out);}catch{throw new HttpError(400,'INVALID_UTF8');}}
export async function readJson(req:Request,max:number){const s=await readBody(req,max);if(!s.trim())throw new HttpError(400,'INVALID_JSON');try{const v=JSON.parse(s);if(!v||typeof v!=='object'||Array.isArray(v))throw new Error();return v as Record<string,unknown>;}catch{throw new HttpError(400,'INVALID_JSON');}}
const bytes=(s:string)=>new TextEncoder().encode(s).byteLength;
export function agentId(x:unknown,allowed:string[],c:Config){if(typeof x!=='string'||!x||bytes(x)>c.maxAgentIdBytes||!/^[A-Za-z0-9_.:-]+$/u.test(x))throw new HttpError(422,'INVALID_AGENT_ID');if(allowed.length&&!allowed.includes(x))throw new HttpError(403,'UNKNOWN_AGENT');return x;}
export function workflow(x:unknown,c:Config,allowed:string[]){if(typeof x!=='string'||!flowOk(x,c.maxWorkflowBytes))throw new HttpError(422,'INVALID_WORKFLOW');if(allowed.length&&!allowed.includes(x))throw new HttpError(422,'UNSAFE_WORKFLOW');return x;}
function task(x:unknown,c:Config){if(typeof x!=='string'||bytes(x)>c.maxTaskIdBytes||!/^[A-Za-z0-9_.:-]+$/u.test(x)||x.includes('..'))throw new HttpError(422,'INVALID_TASK_ID');return x;}
export function runUrl(x:unknown,repo:string|undefined,c:Config){if(x===undefined)return undefined;if(typeof x!=='string'||bytes(x)>c.maxRunUrlBytes)throw new HttpError(422,'INVALID_RUN_URL');if(!repo)throw new HttpError(422,'UNSAFE_RUN_URL');let u:URL;try{u=new URL(x);}catch{throw new HttpError(422,'INVALID_RUN_URL');}if(u.protocol!=='https:'||!['github.com','api.github.com'].includes(u.hostname)||u.username||u.password||u.search||u.hash)throw new HttpError(422,'UNSAFE_RUN_URL');const prefix=u.hostname==='github.com'?'/'+repo+'/actions/runs/':'/repos/'+repo+'/actions/runs/';const runId=u.pathname.startsWith(prefix)?u.pathname.slice(prefix.length):'';if(!/^\d+$/u.test(runId))throw new HttpError(422,'UNSAFE_RUN_URL');return x;}
export function heartbeatBody(x:Record<string,unknown>,c:Config,agents:string[],repo:string|undefined,allowed:string[]){const agent=agentId(x.agent_id,agents,c);const status=x.status;if(status!=='running'&&status!=='completed'&&status!=='failed'&&status!=='pending')throw new HttpError(422,'INVALID_STATUS');const pending=x.pending;if(typeof pending!=='number'||!Number.isSafeInteger(pending)||pending<0)throw new HttpError(422,'INVALID_PENDING');const h:HeartbeatRecord={agentId:agent,status,pending,receivedAt:typeof x.received_at==='number'&&Number.isSafeInteger(x.received_at)&&x.received_at>0?x.received_at:Date.now()};if(x.task_id!==undefined)h.taskId=task(x.task_id,c);if(x.checkpoint!==undefined){if(typeof x.checkpoint!=='string'||bytes(x.checkpoint)>c.maxCheckpointBytes)throw new HttpError(422,'INVALID_CHECKPOINT');h.checkpoint=x.checkpoint;}if(x.workflow!==undefined)h.workflow=workflow(x.workflow,c,allowed);if(x.run_url!==undefined){const validatedRunUrl=runUrl(x.run_url,repo,c);if(validatedRunUrl!==undefined)h.runUrl=validatedRunUrl;}if(x.run_id!==undefined){if(!Number.isSafeInteger(x.run_id)||Number(x.run_id)<=0)throw new HttpError(422,'INVALID_RUN_ID');h.runId=Number(x.run_id);}if((h.runId!==undefined||h.runUrl)&&!h.workflow)throw new HttpError(422,'WORKFLOW_REQUIRED');return h;}
export function dispatchRecord(x:Record<string,unknown>,c:Config,agents:string[],repo:string|undefined,allowed:string[]):DispatchRecord{const d={timestamp:x.timestamp,agentId:x.agent_id,workflow:x.workflow,runIdentity:x.run_identity,result:x.result,reason:x.reason} as DispatchRecord;if(!Number.isSafeInteger(d.timestamp)||d.timestamp<=0)throw new HttpError(422,'INVALID_TIMESTAMP');agentId(d.agentId,agents,c);workflow(d.workflow,c,allowed);if(d.runIdentity!==undefined&&(typeof d.runIdentity!=='string'||bytes(d.runIdentity)>c.maxRunIdentityBytes||!/^[A-Za-z0-9_.:-]+$/u.test(d.runIdentity)))throw new HttpError(422,'INVALID_RUN_IDENTITY');if(!['reserved','ok','fail','cancelled'].includes(d.result))throw new HttpError(422,'INVALID_RESULT');if(!['stale-running','failed','pending-not-continued','manual','cancellation'].includes(d.reason))throw new HttpError(422,'INVALID_REASON');return d;}
export async function stub(env:Env,id:string):Promise<DurableObjectStubLike>{const x=env.AGENT_STATE.idFromName(id);return env.AGENT_STATE.get(x);}
async function readRpcJson(r:Response,max:number){
  const cl=r.headers.get('Content-Length');
  if(cl&&Number.isFinite(Number(cl))&&Number(cl)>max)throw new Error('DO_RESPONSE_TOO_LARGE');
  const reader=r.body?.getReader();
  if(!reader)throw new Error('DO_EMPTY_RESPONSE');
  const parts:Uint8Array[]=[];let total=0;
  try{
    for(;;){
      const x=await reader.read();
      if(x.done)break;
      total+=x.value.byteLength;
      if(total>max){await reader.cancel();throw new Error('DO_RESPONSE_TOO_LARGE');}
      parts.push(x.value);
    }
  }finally{reader.releaseLock();}
  const out=new Uint8Array(total);let o=0;
  for(const p of parts){out.set(p,o);o+=p.byteLength;}
  try{return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(out)) as unknown;}
  catch{throw new Error('DO_INVALID_JSON');}
}
export async function rpc<T>(s:DurableObjectStubLike,path:string,body?:unknown,max=CORE_LIMITS.maxResponseBytes){
  const init:RequestInit={method:body===undefined?'GET':'POST'};if(body!==undefined){init.headers={'content-type':'application/json'};init.body=JSON.stringify(body);}const r=await s.fetch(new Request('https://agent-state/'+path,init));
  const j=await readRpcJson(r,max);
  if(!r.ok)throw new Error(typeof j==='object'&&j!==null&&'error' in j?String((j as {error?:unknown}).error??'DO_FAILURE'):'DO_FAILURE');
  return j as T;
}
export async function allowRate(env:Env,fp:string,agent:string,bucket:keyof Config['rate'],c:Config){
  const st=await stub(env,agent);
  return (await rpc<{allowed:boolean;retryAt:number}>(st,'consumeRateLimit',{bucket,fp,at:Date.now(),windowMs:c.rate[bucket].windowMs,limit:c.rate[bucket].limit})).allowed;
}
export class GitHubClient{
  private readonly env: Env;
  private readonly g: GithubConfig;
  constructor(env: Env, g: GithubConfig){this.env = env; this.g = g;}private async request(path:string,method='GET',body?:unknown){if(!this.env.GITHUB_TOKEN||!path.startsWith('/repos/'+this.g.repository+'/'))throw new Error('UNSAFE_GITHUB_TARGET');const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),this.g.githubTimeoutMs);try{const init:RequestInit={method,headers:{Authorization:'Bearer '+this.env.GITHUB_TOKEN,Accept:'application/vnd.github+json','X-GitHub-Api-Version':this.g.apiVersion,'Content-Type':'application/json'},redirect:'error',signal:ctl.signal};if(body!==undefined)init.body=JSON.stringify(body);const r=await fetch('https://api.github.com'+path,init);const reader=r.body?.getReader();const parts:Uint8Array[]=[];let total=0;if(reader){try{for(;;){const x=await reader.read();if(x.done)break;total+=x.value.byteLength;if(total>this.g.maxResponseBytes){await reader.cancel();throw new Error('GITHUB_RESPONSE_TOO_LARGE');}parts.push(x.value);}}finally{reader.releaseLock();}}const b=new Uint8Array(total);let o=0;for(const p of parts){b.set(p,o);o+=p.byteLength;}const text=new TextDecoder('utf-8',{fatal:true}).decode(b);if(!r.ok)throw new Error('GITHUB_HTTP_'+r.status);let data:unknown=null;try{if(text)data=JSON.parse(text);}catch{throw new Error('GITHUB_INVALID_JSON');}return {status:r.status,data};}finally{clearTimeout(timer);}} async dispatch(agent:string,reason:string){const p='/repos/'+this.g.repository+'/actions/workflows/'+encodeURIComponent(this.g.workflow)+'/dispatches';const r=await this.request(p,'POST',{ref:this.g.ref,inputs:{agent_id:agent,reason}});if(r.status!==204)throw new Error('GITHUB_DISPATCH_FALSE_SUCCESS');} async run(runId:number){const r=await this.request('/repos/'+this.g.repository+'/actions/runs/'+runId);if(r.status!==200||!r.data||typeof r.data!=='object')throw new Error('GITHUB_RUN_INVALID');return r.data as Record<string,unknown>;} async cancel(runId:number){const r=await this.request('/repos/'+this.g.repository+'/actions/runs/'+runId+'/cancel','POST');if(r.status!==202)throw new Error('GITHUB_CANCEL_FALSE_SUCCESS');}}
export async function decide(env:Env,metrics:Metrics){const loaded=loadConfig(env);if(!loaded||!loaded.github||loaded.agents.length===0){metrics.inc('verify_fail');return;}const {config,agents,github}=loaded;if(!github.autoDispatch&&!github.enableCancel){metrics.inc('verify_pass');return;}const gh=new GitHubClient(env,github);for(const id of agents.slice(0,config.maxStatusAgents)){try{const s=await rpc<{state:AgentState|null;heartbeat:HeartbeatRecord|null}>(await stub(env,id),'getSnapshot');const h=s.heartbeat,st=s.state;if(!h){metrics.inc('verify_pass');continue;}const age=Date.now()-h.receivedAt;if(h.status==='completed'){metrics.inc('verify_pass');continue;}if(github.autoDispatch&&h.status==='failed'&&!st?.breakerTripped){const r=await rpc<ReserveResult>(await stub(env,id),'reserveDispatch',{record:{agentId:id,workflow:github.workflow,reason:'failed'},at:Date.now(),maxPerHour:config.maxDispatchesPerHour,windowMs:config.dispatchWindowMs,minGap:config.minGapMinutes});if(r.accepted){try{await gh.dispatch(id,'failed');await rpc(await stub(env,id),'appendDispatch',{timestamp:Date.now(),agentId:id,workflow:github.workflow,result:'ok',reason:'failed'});metrics.inc('dispatch_ok');}catch{await rpc(await stub(env,id),'appendDispatch',{timestamp:Date.now(),agentId:id,workflow:github.workflow,result:'fail',reason:'failed'});metrics.inc('dispatch_fail');}}else metrics.inc('limit_hit');}
 else if(github.autoDispatch&&h.status==='pending'&&age>config.pendingNotContinuedMs&&!st?.breakerTripped){const r=await rpc<ReserveResult>(await stub(env,id),'reserveDispatch',{record:{agentId:id,workflow:github.workflow,reason:'pending-not-continued'},at:Date.now(),maxPerHour:config.maxDispatchesPerHour,windowMs:config.dispatchWindowMs,minGap:config.minGapMinutes});if(r.accepted){try{await gh.dispatch(id,'pending-not-continued');await rpc(await stub(env,id),'appendDispatch',{timestamp:Date.now(),agentId:id,workflow:github.workflow,result:'ok',reason:'pending-not-continued'});metrics.inc('dispatch_ok');}catch{await rpc(await stub(env,id),'appendDispatch',{timestamp:Date.now(),agentId:id,workflow:github.workflow,result:'fail',reason:'pending-not-continued'});metrics.inc('dispatch_fail');}}else metrics.inc('limit_hit');}
 else if(h.status==='running'&&age>config.staleRunningMs){let cancelled=false;if(github.enableCancel&&h.workflow===github.workflow&&h.runId&&h.runUrl&&age>config.cancelStaleRunningMs){try{const runPath=github.workflow.startsWith('.github/workflows/')?github.workflow:'.github/workflows/'+github.workflow;const runUrlOk=(()=>{try{const u=new URL(h.runUrl!);const prefix=u.hostname==='github.com'?'/'+github.repository+'/actions/runs/':'/repos/'+github.repository+'/actions/runs/';return u.protocol==='https:'&&!u.username&&!u.password&&!u.search&&!u.hash&&u.pathname===prefix+String(h.runId);}catch{return false;}})();if(!runUrlOk)throw new Error('RUN_IDENTITY_AMBIGUOUS');const run=await gh.run(h.runId);const runMatchesId=typeof run.id==='number'&&run.id===h.runId;const runMatchesStatus=typeof run.status==='string'&&['queued','in_progress','waiting'].includes(run.status);const runMatchesWorkflow=run.path===runPath;const repository=run.repository;const runMatchesRepository=Boolean(repository&&typeof repository==='object'&&(repository as {full_name?:unknown}).full_name===github.repository);const same=runMatchesId&&runMatchesStatus&&runMatchesWorkflow&&runMatchesRepository;if(same){await rpc(await stub(env,id),'appendDispatch',{timestamp:Date.now(),agentId:id,workflow:github.workflow,runIdentity:String(h.runId),result:'reserved',reason:'cancellation'});await gh.cancel(h.runId);await rpc(await stub(env,id),'appendDispatch',{timestamp:Date.now(),agentId:id,workflow:github.workflow,runIdentity:String(h.runId),result:'cancelled',reason:'cancellation'});cancelled=true;}}catch{cancelled=false;}}if(!cancelled&&github.autoDispatch&&!h.runId&&!st?.breakerTripped){const r=await rpc<ReserveResult>(await stub(env,id),'reserveDispatch',{record:{agentId:id,workflow:github.workflow,reason:'stale-running'},at:Date.now(),maxPerHour:config.maxDispatchesPerHour,windowMs:config.dispatchWindowMs,minGap:config.minGapMinutes});if(r.accepted){try{await gh.dispatch(id,'stale-running');await rpc(await stub(env,id),'appendDispatch',{timestamp:Date.now(),agentId:id,workflow:github.workflow,result:'ok',reason:'stale-running'});metrics.inc('dispatch_ok');}catch{await rpc(await stub(env,id),'appendDispatch',{timestamp:Date.now(),agentId:id,workflow:github.workflow,result:'fail',reason:'stale-running'});metrics.inc('dispatch_fail');}}else metrics.inc('limit_hit');}}metrics.inc('verify_pass');}catch{metrics.inc('verify_fail');}}}
