version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    labels:
      - security
    groups:
      npm-minor-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
    open-pull-requests-limit: 10
    labels:
      - security
    groups:
      github-actions-updates:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
