name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
categories:
  - title: "Features"
    labels: ["feature", "enhancement", "feat"]
  - title: "Improvements"
    labels: ["perf", "refactor"]
  - title: "Fixes"
    labels: ["fix", "bugfix", "bug", "hotfix", "revert"]
  - title: "Tests"
    labels: ["tests", "testing"]
  - title: "CI / Infrastructure"
    labels: ["ci", "build", "devops"]
  - title: "Documentation"
    labels: ["docs"]
  - title: "Chores"
    labels: ["chore", "maintenance"]
  - type: "pre-exclude"
    label: "skip-changelog"
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
