import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
const root=resolve(import.meta.dirname,"..");
const pkg=JSON.parse(readFileSync(join(root,"package.json"),"utf8"));
const lock=JSON.parse(readFileSync(join(root,"package-lock.json"),"utf8"));
const ts=JSON.parse(readFileSync(join(root,"tsconfig.json"),"utf8"));
const wr=readFileSync(join(root,"wrangler.toml"),"utf8");
const vt=readFileSync(join(root,"vitest.config.ts"),"utf8");
if(pkg.private!==true||pkg.type!=="module"||pkg.engines?.node!=="22.x") throw new Error("WORKER_CONFIG_NOT_ISOLATED");
if(pkg.workspaces||pkg.packageManager) throw new Error("ROOT_WORKSPACE_DEPENDENCY");
if(lock.lockfileVersion!==3||lock.packages?.[""]?.name!==pkg.name) throw new Error("LOCKFILE_INVALID");
for(const v of Object.values(pkg.devDependencies||{})) if(typeof v!=="string"||!/^[0-9]+\\.[0-9]+\\.[0-9]+$/.test(v)) throw new Error("FLOATING_DEPENDENCY");
if(ts.compilerOptions?.strict!==true||ts.compilerOptions?.noEmit!==true||ts.compilerOptions?.module!=="ESNext") throw new Error("TSCONFIG_FAIL_CLOSED");
if(!ts.compilerOptions?.lib?.includes("DOM")) throw new Error("TSCONFIG_WORKERS_GLOBALS_MISSING");
if(/^\\s*(?:AGENT_TOKEN|AGENT_TOKEN_PREV|ADMIN_TOKEN|GITHUB_TOKEN)\\s*=/m.test(wr+vt)) throw new Error("SECRET_EMBEDDED");
if(/\\b(?:eval|Function)\\s*\\(/.test(wr+vt)) throw new Error("DYNAMIC_CODE_EVAL");
if(/\\b(?:git\\s+(?:push|merge|rebase|reset|checkout|switch)|wrangler\\s+deploy)\\b/i.test(wr)) throw new Error("MUTATION_COMMAND_IN_CONFIG");
console.log("WORKER_CONFIG=FAIL_CLOSED");
console.log("SECRET_SOURCE=WORKER_SECRET_ONLY");
console.log("CANONICAL_TARGET=LOCKED");
console.log("DURABLE_OBJECT=BOUND");
console.log("MIGRATION=VALID");
console.log("NODE_VERSION=22");
console.log("WATCHDOG_SECURITY=PASS");
