import type { Locale } from '@/lib/i18n';

export type FilterMaskCopy = Readonly<{
  title: 'Filter Mask';
  selected: string;
  liveCamera: string;
  startCamera: string;
  stop: string;
  switchCamera: string;
  torchOn: string;
  torchOff: string;
  torchUnsupported: string;
  torchFailed: string;
  photo: string;
  recordVideo: string;
  recording: string;
  stopRecording: string;
  pauseRecording: string;
  resumeRecording: string;
  cancelRecording: string;
  recordingPerformance: string;
  recordingBackendGpu: string;
  recordingBackendCanvas: string;
  recordingWakeLockUnavailable: string;
  cameraUnavailable: string;
  cameraDenied: string;
  recordingUnsupported: string;
  recordingUnavailable: string;
  recordingFailed: string;
  recordingStartFailed: string;
  searchFilters: string;
  searchPlaceholder: string;
  filterFamilies: string;
  all: string;
  favorites: string;
  recent: string;
  favorite: string;
  favoriteActive: string;
  reset: string;
  savePreset: string;
  presetName: string;
  presetNamePlaceholder: string;
  presets: string;
  deletePreset: string;
  cameraFraming: string;
  zoom: string;
  mirrorOn: string;
  mirrorOff: string;
  intensity: string;
  aspectRatio: string;
  captureQuality: string;
  quality720: string;
  quality1080: string;
  qualityChangeFailed: string;
  download: string;
  share: string;
  shareSetup: string;
  shareSetupUnsupported: string;
  shareSetupFailed: string;
  shareUnsupported: string;
  shareFileUnsupported: string;
  shareFailed: string;
  family: Readonly<Record<'color' | 'mood' | 'cinematic' | 'mono' | 'retro', string>>;
}>;

const EN: FilterMaskCopy = {
  title: 'Filter Mask',
  selected: 'Selected',
  liveCamera: 'live camera',
  startCamera: 'Start camera',
  stop: 'Stop',
  switchCamera: 'Switch camera',
  torchOn: 'Torch on',
  torchOff: 'Torch off',
  torchUnsupported: 'Torch is not available on this camera.',
  torchFailed: 'Torch could not be changed.',
  photo: 'Photo',
  recordVideo: 'Record video',
  recording: 'Recording',
  stopRecording: 'Stop recording',
  pauseRecording: 'Pause recording',
  resumeRecording: 'Resume recording',
  cancelRecording: 'Cancel recording',
  recordingPerformance: 'Performance',
  recordingBackendGpu: 'GPU',
  recordingBackendCanvas: 'Canvas',
  recordingWakeLockUnavailable: 'Screen wake lock is not available; recording will continue normally.',
  cameraUnavailable: 'Camera is not available in this browser.',
  cameraDenied: 'Camera or microphone access was denied or unavailable.',
  recordingUnsupported: 'Video recording with live effects is not supported in this browser.',
  recordingUnavailable: 'Video recording is unavailable.',
  recordingFailed: 'Video recording failed.',
  recordingStartFailed: 'Video recording could not be started.',
  searchFilters: 'Search filters',
  searchPlaceholder: 'Search filters',
  filterFamilies: 'Filter families',
  all: 'All',
  favorites: 'Favorites',
  recent: 'Recent',
  favorite: '☆ Favorite',
  favoriteActive: '★ Favorite',
  reset: 'Reset filter',
  savePreset: 'Save preset',
  presetName: 'Preset name',
  presetNamePlaceholder: 'Name this creator preset',
  presets: 'Presets',
  deletePreset: 'Delete preset',
  cameraFraming: 'Camera framing',
  zoom: 'Zoom',
  mirrorOn: 'Mirror on',
  mirrorOff: 'Mirror off',
  intensity: 'Intensity',
  aspectRatio: 'Capture aspect ratio',
  captureQuality: 'Capture quality',
  quality720: '720p standard',
  quality1080: '1080p high',
  qualityChangeFailed: 'Capture quality could not be changed for the active camera.',
  download: 'Download result',
  share: 'Share result',
  shareSetup: 'Share filter setup',
  shareSetupUnsupported: 'Filter setup sharing is not available. Copy the current URL instead.',
  shareSetupFailed: 'Could not share the filter setup. Copy the current URL instead.',
  shareUnsupported: 'Sharing is not available in this browser. Use Download result instead.',
  shareFileUnsupported: 'This device cannot share this file. Use Download result instead.',
  shareFailed: 'Sharing failed. Use Download result instead.',
  family: { color: 'Color', mood: 'Mood', cinematic: 'Cinematic', mono: 'Mono', retro: 'Retro' },
};

const FILTER_MASK_NEW_COPY: Readonly<Record<Locale, Partial<FilterMaskCopy>>> = {
  en: {},
  ar: { presetName: "اسم الإعداد", presetNamePlaceholder: "سمِّ إعداد المبدع هذا", captureQuality: "جودة الالتقاط", liveCamera: 'الكاميرا المباشرة', torchOn: 'الكشاف مفعّل', torchOff: 'الكشاف متوقف', torchUnsupported: 'الكشاف غير متاح في هذه الكاميرا.', torchFailed: 'تعذر تغيير الكشاف.', pauseRecording: 'إيقاف التسجيل مؤقتًا', resumeRecording: 'استئناف التسجيل', cancelRecording: 'إلغاء التسجيل', recordingPerformance: 'الأداء', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'قفل إبقاء الشاشة نشطًا غير متاح؛ سيستمر التسجيل بشكل طبيعي.', quality720: "720p قياسي", quality1080: '1080p عالٍ', qualityChangeFailed: 'تعذر تغيير جودة الالتقاط للكاميرا النشطة.'  },
  es: { presetName: "Nombre del preajuste", presetNamePlaceholder: "Nombra este preajuste de creador", captureQuality: "Calidad de captura", liveCamera: 'cámara en directo', torchOn: 'Linterna activada', torchOff: 'Linterna desactivada', torchUnsupported: 'La linterna no está disponible en esta cámara.', torchFailed: 'No se pudo cambiar la linterna.', pauseRecording: 'Pausar grabación', resumeRecording: 'Reanudar grabación', cancelRecording: 'Cancelar grabación', recordingPerformance: 'Rendimiento', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'El bloqueo de activación de pantalla no está disponible; la grabación continuará normalmente.', quality720: "720p estándar", quality1080: '1080p alta', qualityChangeFailed: 'No se pudo cambiar la calidad de captura para la cámara activa.'  },
  fr: { presetName: "Nom du préréglage", presetNamePlaceholder: "Nommez ce préréglage du créateur", captureQuality: "Qualité de capture", liveCamera: 'caméra en direct', torchOn: 'Torche activée', torchOff: 'Torche désactivée', torchUnsupported: 'La torche n’est pas disponible sur cette caméra.', torchFailed: 'Impossible de modifier la torche.', pauseRecording: 'Mettre l’enregistrement en pause', resumeRecording: 'Reprendre l’enregistrement', cancelRecording: 'Annuler l’enregistrement', recordingPerformance: 'Performances', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'Le maintien de l’écran actif n’est pas disponible ; l’enregistrement continuera normalement.', quality720: "720p classique", quality1080: '1080p haute', qualityChangeFailed: 'Impossible de modifier la qualité de capture pour la caméra active.'  },
  de: { presetName: "Presetname", presetNamePlaceholder: "Dieses Creator-Preset benennen", captureQuality: "Aufnahmequalität", liveCamera: 'Live-Kamera', torchOn: 'Taschenlampe an', torchOff: 'Taschenlampe aus', torchUnsupported: 'Die Taschenlampe ist auf dieser Kamera nicht verfügbar.', torchFailed: 'Die Taschenlampe konnte nicht geändert werden.', pauseRecording: 'Aufnahme pausieren', resumeRecording: 'Aufnahme fortsetzen', cancelRecording: 'Aufnahme abbrechen', recordingPerformance: 'Leistung', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'Die Bildschirmaktivierung ist nicht verfügbar; die Aufnahme wird normal fortgesetzt.', quality720: "720p normal", quality1080: '1080p hoch', qualityChangeFailed: 'Die Aufnahmequalität der aktiven Kamera konnte nicht geändert werden.'  },
  hi: { presetName: "प्रीसेट का नाम", presetNamePlaceholder: "इस क्रिएटर प्रीसेट का नाम दें", captureQuality: "कैप्चर गुणवत्ता", liveCamera: 'लाइव कैमरा', torchOn: 'फ्लैशलाइट चालू', torchOff: 'फ्लैशलाइट बंद', torchUnsupported: 'इस कैमरे पर फ्लैशलाइट उपलब्ध नहीं है।', torchFailed: 'फ्लैशलाइट बदली नहीं जा सकी।', pauseRecording: 'रिकॉर्डिंग रोकें', resumeRecording: 'रिकॉर्डिंग फिर शुरू करें', cancelRecording: 'रिकॉर्डिंग रद्द करें', recordingPerformance: 'प्रदर्शन', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'स्क्रीन वेक लॉक उपलब्ध नहीं है; रिकॉर्डिंग सामान्य रूप से जारी रहेगी।', quality720: "720p मानक", quality1080: '1080p उच्च', qualityChangeFailed: 'सक्रिय कैमरे की कैप्चर गुणवत्ता बदली नहीं जा सकी।'  },
  id: { presetName: "Nama preset", presetNamePlaceholder: "Beri nama preset kreator ini", captureQuality: "Kualitas pengambilan", liveCamera: 'kamera langsung', torchOn: 'Senter aktif', torchOff: 'Senter nonaktif', torchUnsupported: 'Senter tidak tersedia pada kamera ini.', torchFailed: 'Senter tidak dapat diubah.', pauseRecording: 'Jeda rekaman', resumeRecording: 'Lanjutkan rekaman', cancelRecording: 'Batalkan rekaman', recordingPerformance: 'Performa', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'Penguncian layar tetap aktif tidak tersedia; rekaman akan berlanjut normal.', quality720: "720p standar", quality1080: '1080p tinggi', qualityChangeFailed: 'Kualitas pengambilan tidak dapat diubah untuk kamera aktif.'  },
  it: { presetName: "Nome del preset", presetNamePlaceholder: "Dai un nome a questo preset", captureQuality: "Qualità di acquisizione", liveCamera: 'fotocamera live', torchOn: 'Torcia attiva', torchOff: 'Torcia disattiva', torchUnsupported: 'La torcia non è disponibile su questa fotocamera.', torchFailed: 'Impossibile modificare la torcia.', pauseRecording: 'Metti in pausa la registrazione', resumeRecording: 'Riprendi la registrazione', cancelRecording: 'Annulla registrazione', recordingPerformance: 'Prestazioni', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'Il blocco di riattivazione dello schermo non è disponibile; la registrazione continuerà normalmente.', quality720: "720p normale", quality1080: '1080p alta', qualityChangeFailed: 'Impossibile modificare la qualità di acquisizione per la fotocamera attiva.'  },
  ja: { presetName: "プリセット名", presetNamePlaceholder: "このクリエータープリセットに名前を付ける", captureQuality: "キャプチャ品質", liveCamera: 'ライブカメラ', torchOn: 'ライトオン', torchOff: 'ライトオフ', torchUnsupported: 'このカメラではライトを利用できません。', torchFailed: 'ライトを変更できませんでした。', pauseRecording: '録画を一時停止', resumeRecording: '録画を再開', cancelRecording: '録画をキャンセル', recordingPerformance: 'パフォーマンス', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: '画面のスリープ防止は利用できません。録画は通常どおり続行されます。', quality720: "720p 標準", quality1080: '1080p 高画質', qualityChangeFailed: 'アクティブなカメラの撮影品質を変更できませんでした。'  },
  ko: { presetName: "프리셋 이름", presetNamePlaceholder: "이 크리에이터 프리셋에 이름 지정", captureQuality: "캡처 품질", liveCamera: '라이브 카메라', torchOn: '손전등 켜짐', torchOff: '손전등 꺼짐', torchUnsupported: '이 카메라에서는 손전등을 사용할 수 없습니다.', torchFailed: '손전등을 변경할 수 없습니다.', pauseRecording: '녹화 일시중지', resumeRecording: '녹화 재개', cancelRecording: '녹화 취소', recordingPerformance: '성능', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: '화면 깨우기 잠금을 사용할 수 없습니다. 녹화는 정상적으로 계속됩니다.', quality720: "720p 표준", quality1080: '1080p 고화질', qualityChangeFailed: '활성 카메라의 캡처 품질을 변경할 수 없습니다.'  },
  ms: { presetName: "Nama pratetap", presetNamePlaceholder: "Namakan pratetap pencipta ini", captureQuality: "Kualiti tangkapan", liveCamera: 'kamera langsung', torchOn: 'Lampu suluh dihidupkan', torchOff: 'Lampu suluh dimatikan', torchUnsupported: 'Lampu suluh tidak tersedia pada kamera ini.', torchFailed: 'Lampu suluh tidak dapat diubah.', pauseRecording: 'Jeda rakaman', resumeRecording: 'Sambung rakaman', cancelRecording: 'Batalkan rakaman', recordingPerformance: 'Prestasi', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'Kunci kekal skrin aktif tidak tersedia; rakaman akan diteruskan seperti biasa.', quality720: "720p biasa", quality1080: '1080p tinggi', qualityChangeFailed: 'Kualiti tangkapan tidak dapat diubah untuk kamera aktif.'  },
  nl: { presetName: "Naam van voorinstelling", presetNamePlaceholder: "Geef deze creator-voorinstelling een naam", captureQuality: "Opnamekwaliteit", liveCamera: 'livecamera', torchOn: 'Zaklamp aan', torchOff: 'Zaklamp uit', torchUnsupported: 'De zaklamp is niet beschikbaar op deze camera.', torchFailed: 'De zaklamp kon niet worden gewijzigd.', pauseRecording: 'Opname pauzeren', resumeRecording: 'Opname hervatten', cancelRecording: 'Opname annuleren', recordingPerformance: 'Prestaties', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'Schermactivering is niet beschikbaar; de opname gaat normaal door.', quality720: "720p standaard", quality1080: '1080p hoog', qualityChangeFailed: 'De opnamekwaliteit van de actieve camera kon niet worden gewijzigd.'  },
  pl: { presetName: "Nazwa presetu", presetNamePlaceholder: "Nadaj nazwę temu presetowi twórcy", captureQuality: "Jakość nagrywania", liveCamera: 'kamera na żywo', torchOn: 'Latarka włączona', torchOff: 'Latarka wyłączona', torchUnsupported: 'Latarka nie jest dostępna w tej kamerze.', torchFailed: 'Nie udało się zmienić latarki.', pauseRecording: 'Wstrzymaj nagrywanie', resumeRecording: 'Wznów nagrywanie', cancelRecording: 'Anuluj nagrywanie', recordingPerformance: 'Wydajność', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'Blokada wybudzenia ekranu jest niedostępna; nagrywanie będzie trwać normalnie.', quality720: "720p standardowa", quality1080: '1080p wysoka', qualityChangeFailed: 'Nie udało się zmienić jakości przechwytywania dla aktywnej kamery.'  },
  pt: { presetName: "Nome da predefinição", presetNamePlaceholder: "Dê um nome a esta predefinição de criador", captureQuality: "Qualidade de captura", liveCamera: 'câmera ao vivo', torchOn: 'Lanterna ligada', torchOff: 'Lanterna desligada', torchUnsupported: 'A lanterna não está disponível nesta câmera.', torchFailed: 'Não foi possível alterar a lanterna.', pauseRecording: 'Pausar gravação', resumeRecording: 'Retomar gravação', cancelRecording: 'Cancelar gravação', recordingPerformance: 'Desempenho', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'O bloqueio para manter a tela ativa não está disponível; a gravação continuará normalmente.', quality720: "720p padrão", quality1080: '1080p alta', qualityChangeFailed: 'Não foi possível alterar a qualidade de captura da câmera ativa.'  },
  ru: { presetName: "Название пресета", presetNamePlaceholder: "Назовите этот пресет", captureQuality: "Качество захвата", liveCamera: 'прямая камера', torchOn: 'Фонарик включён', torchOff: 'Фонарик выключен', torchUnsupported: 'Фонарик недоступен на этой камере.', torchFailed: 'Не удалось изменить состояние фонарика.', pauseRecording: 'Приостановить запись', resumeRecording: 'Продолжить запись', cancelRecording: 'Отменить запись', recordingPerformance: 'Производительность', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'Блокировка сна экрана недоступна; запись продолжится в обычном режиме.', quality720: "720p стандартное", quality1080: '1080p высокое', qualityChangeFailed: 'Не удалось изменить качество съёмки для активной камеры.'  },
  sv: { presetName: "Namn på förinställning", presetNamePlaceholder: "Namnge denna skaparförinställning", captureQuality: "Inspelningskvalitet", liveCamera: 'livekamera', torchOn: 'Ficklampa på', torchOff: 'Ficklampa av', torchUnsupported: 'Ficklampan är inte tillgänglig på den här kameran.', torchFailed: 'Det gick inte att ändra ficklampan.', pauseRecording: 'Pausa inspelning', resumeRecording: 'Återuppta inspelning', cancelRecording: 'Avbryt inspelning', recordingPerformance: 'Prestanda', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'Skärmväckning är inte tillgänglig; inspelningen fortsätter normalt.', quality720: "720p normal", quality1080: '1080p hög', qualityChangeFailed: 'Det gick inte att ändra inspelningskvaliteten för den aktiva kameran.'  },
  th: { presetName: "ชื่อพรีเซ็ต", presetNamePlaceholder: "ตั้งชื่อพรีเซ็ตครีเอเตอร์นี้", captureQuality: "คุณภาพการจับภาพ", liveCamera: 'กล้องถ่ายทอดสด', torchOn: 'ไฟฉายเปิด', torchOff: 'ไฟฉายปิด', torchUnsupported: 'กล้องนี้ไม่รองรับไฟฉาย', torchFailed: 'ไม่สามารถเปลี่ยนไฟฉายได้', pauseRecording: 'หยุดการบันทึกชั่วคราว', resumeRecording: 'บันทึกต่อ', cancelRecording: 'ยกเลิกการบันทึก', recordingPerformance: 'ประสิทธิภาพ', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'ไม่สามารถล็อกหน้าจอให้ตื่นได้ การบันทึกจะดำเนินต่อไปตามปกติ', quality720: "720p มาตรฐาน", quality1080: '1080p คุณภาพสูง', qualityChangeFailed: 'ไม่สามารถเปลี่ยนคุณภาพการจับภาพสำหรับกล้องที่ใช้งานอยู่ได้'  },
  tr: { presetName: "Ön ayar adı", presetNamePlaceholder: "Bu içerik üretici ön ayarını adlandırın", captureQuality: "Yakalama kalitesi", liveCamera: 'canlı kamera', torchOn: 'Fener açık', torchOff: 'Fener kapalı', torchUnsupported: 'Bu kamerada fener kullanılamıyor.', torchFailed: 'Fener değiştirilemedi.', pauseRecording: 'Kaydı duraklat', resumeRecording: 'Kaydı sürdür', cancelRecording: 'Kaydı iptal et', recordingPerformance: 'Performans', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'Ekranı uyanık tutma kilidi kullanılamıyor; kayıt normal şekilde devam edecek.', quality720: "720p standart", quality1080: '1080p yüksek', qualityChangeFailed: 'Etkin kamera için çekim kalitesi değiştirilemedi.'  },
  uk: { presetName: "Назва пресету", presetNamePlaceholder: "Назвіть цей пресет", captureQuality: "Якість захоплення", liveCamera: 'камера наживо', torchOn: 'Ліхтарик увімкнено', torchOff: 'Ліхтарик вимкнено', torchUnsupported: 'Ліхтарик недоступний на цій камері.', torchFailed: 'Не вдалося змінити стан ліхтарика.', pauseRecording: 'Призупинити запис', resumeRecording: 'Продовжити запис', cancelRecording: 'Скасувати запис', recordingPerformance: 'Продуктивність', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'Блокування сну екрана недоступне; запис продовжиться у звичайному режимі.', quality720: "720p стандарт", quality1080: '1080p висока', qualityChangeFailed: 'Не вдалося змінити якість зйомки для активної камери.'  },
  vi: { presetName: "Tên cài đặt", presetNamePlaceholder: "Đặt tên cho cài đặt dành cho nhà sáng tạo này", captureQuality: "Chất lượng chụp", liveCamera: 'camera trực tiếp', torchOn: 'Bật đèn pin', torchOff: 'Tắt đèn pin', torchUnsupported: 'Đèn pin không khả dụng trên camera này.', torchFailed: 'Không thể thay đổi đèn pin.', pauseRecording: 'Tạm dừng quay', resumeRecording: 'Tiếp tục quay', cancelRecording: 'Hủy quay', recordingPerformance: 'Hiệu suất', recordingBackendGpu: 'GPU', recordingBackendCanvas: 'Canvas', recordingWakeLockUnavailable: 'Không có khóa đánh thức màn hình; quá trình quay sẽ tiếp tục bình thường.', quality720: "720p tiêu chuẩn", quality1080: '1080p cao', qualityChangeFailed: 'Không thể thay đổi chất lượng chụp cho camera đang hoạt động.'  },
};

export const FILTER_MASK_I18N: Readonly<Record<Locale, FilterMaskCopy>> = {
  ar: { ...EN, selected: 'المحدد', startCamera: 'بدء الكاميرا', stop: 'إيقاف', switchCamera: 'تبديل الكاميرا', photo: 'صورة', recordVideo: 'تسجيل فيديو', stopRecording: 'إيقاف التسجيل', cameraUnavailable: 'الكاميرا غير متاحة في هذا المتصفح.', cameraDenied: 'تم رفض الوصول إلى الكاميرا أو الميكروفون أو أنهما غير متاحين.', recordingUnsupported: 'تسجيل الفيديو مع التأثيرات المباشرة غير مدعوم في هذا المتصفح.', recordingUnavailable: 'تسجيل الفيديو غير متاح.', recordingFailed: 'فشل تسجيل الفيديو.', recordingStartFailed: 'تعذر بدء تسجيل الفيديو.', searchFilters: 'بحث في الفلاتر', searchPlaceholder: 'ابحث عن فلتر', filterFamilies: 'فئات الفلاتر', all: 'الكل', favorites: 'المفضلة', recent: 'الأخيرة', favorite: '☆ مفضلة', favoriteActive: '★ مفضلة', reset: 'إعادة ضبط الفلتر', savePreset: 'حفظ الإعداد', presets: 'الإعدادات المحفوظة', deletePreset: 'حذف الإعداد', cameraFraming: 'إطار الكاميرا', zoom: 'التكبير', mirrorOn: 'المرآة مفعلة', mirrorOff: 'المرآة متوقفة', intensity: 'الشدة', aspectRatio: 'نسبة التصوير', download: 'تنزيل النتيجة', share: 'مشاركة النتيجة', shareSetup: 'مشاركة إعداد الفلتر', shareSetupUnsupported: 'مشاركة إعداد الفلتر غير متاحة. انسخ الرابط الحالي.', shareSetupFailed: 'تعذرت مشاركة إعداد الفلتر. انسخ الرابط الحالي.', shareUnsupported: 'المشاركة غير متاحة في هذا المتصفح. استخدم تنزيل النتيجة.', shareFileUnsupported: 'هذا الجهاز لا يستطيع مشاركة هذا الملف. استخدم تنزيل النتيجة.', shareFailed: 'فشلت المشاركة. استخدم تنزيل النتيجة.', family: { color: 'ألوان', mood: 'مزاج', cinematic: 'سينمائي', mono: 'أحادي', retro: 'ريترو' } , ...FILTER_MASK_NEW_COPY.ar },
  en: EN,
  es: { ...EN, selected: 'Seleccionado', startCamera: 'Iniciar cámara', stop: 'Detener', switchCamera: 'Cambiar cámara', photo: 'Foto', recordVideo: 'Grabar vídeo', stopRecording: 'Detener grabación', cameraUnavailable: 'La cámara no está disponible en este navegador.', cameraDenied: 'Se denegó el acceso a la cámara o al micrófono o no están disponibles.', recordingUnsupported: 'La grabación de vídeo con efectos en directo no es compatible con este navegador.', recordingUnavailable: 'La grabación de vídeo no está disponible.', recordingFailed: 'La grabación de vídeo ha fallado.', recordingStartFailed: 'No se pudo iniciar la grabación de vídeo.', searchFilters: 'Buscar filtros', searchPlaceholder: 'Buscar filtros', filterFamilies: 'Familias de filtros', all: 'Todos', favorites: 'Favoritos', recent: 'Recientes', favorite: '☆ Favorito', favoriteActive: '★ Favorito', reset: 'Restablecer filtro', savePreset: 'Guardar configuración', presets: 'Preajustes', deletePreset: 'Eliminar configuración', cameraFraming: 'Encuadre de cámara', zoom: 'Zoom', mirrorOn: 'Espejo activado', mirrorOff: 'Espejo desactivado', intensity: 'Intensidad', aspectRatio: 'Relación de aspecto', download: 'Descargar resultado', share: 'Compartir resultado', shareSetup: 'Compartir configuración', shareSetupUnsupported: 'No se puede compartir la configuración. Copia la URL actual.', shareSetupFailed: 'No se pudo compartir la configuración. Copia la URL actual.', shareUnsupported: 'La función de compartir no está disponible. Usa Descargar resultado.', shareFileUnsupported: 'Este dispositivo no puede compartir este archivo. Usa Descargar resultado.', shareFailed: 'No se pudo compartir. Usa Descargar resultado.', family: { color: 'Color', mood: 'Ambiente', cinematic: 'Cinemático', mono: 'Mono', retro: 'Retro' } , ...FILTER_MASK_NEW_COPY.es },
  fr: { ...EN, selected: 'Sélectionné', startCamera: 'Démarrer la caméra', stop: 'Arrêter', switchCamera: 'Changer de caméra', photo: 'Photo', recordVideo: 'Enregistrer la vidéo', stopRecording: 'Arrêter l’enregistrement', cameraUnavailable: 'La caméra n’est pas disponible dans ce navigateur.', cameraDenied: 'L’accès à la caméra ou au microphone a été refusé ou est indisponible.', recordingUnsupported: 'L’enregistrement vidéo avec effets en direct n’est pas pris en charge dans ce navigateur.', recordingUnavailable: 'L’enregistrement vidéo est indisponible.', recordingFailed: 'Échec de l’enregistrement vidéo.', recordingStartFailed: 'Impossible de démarrer l’enregistrement vidéo.', searchFilters: 'Rechercher des filtres', searchPlaceholder: 'Rechercher des filtres', filterFamilies: 'Familles de filtres', all: 'Tous', favorites: 'Favoris', recent: 'Récents', favorite: '☆ Favori', favoriteActive: '★ Favori', reset: 'Réinitialiser le filtre', savePreset: 'Enregistrer le préréglage', presets: 'Préréglages', deletePreset: 'Supprimer le préréglage', cameraFraming: 'Cadre de caméra', zoom: 'Zoom', mirrorOn: 'Miroir activé', mirrorOff: 'Miroir désactivé', intensity: 'Intensité', aspectRatio: 'Format de capture', download: 'Télécharger le résultat', share: 'Partager le résultat', shareSetup: 'Partager la configuration', shareSetupUnsupported: 'Le partage de la configuration n’est pas disponible. Copiez l’URL actuelle.', shareSetupFailed: 'Impossible de partager la configuration. Copiez l’URL actuelle.', shareUnsupported: 'Le partage n’est pas disponible. Utilisez Télécharger le résultat.', shareFileUnsupported: 'Cet appareil ne peut pas partager ce fichier. Utilisez Télécharger le résultat.', shareFailed: 'Échec du partage. Utilisez Télécharger le résultat.', family: { color: 'Couleur', mood: 'Ambiance', cinematic: 'Cinéma', mono: 'Mono', retro: 'Rétro' } , ...FILTER_MASK_NEW_COPY.fr },
  de: { ...EN, selected: 'Ausgewählt', startCamera: 'Kamera starten', stop: 'Stopp', switchCamera: 'Kamera wechseln', photo: 'Foto', recordVideo: 'Video aufnehmen', stopRecording: 'Aufnahme stoppen', cameraUnavailable: 'Die Kamera ist in diesem Browser nicht verfügbar.', cameraDenied: 'Der Zugriff auf Kamera oder Mikrofon wurde verweigert oder ist nicht verfügbar.', recordingUnsupported: 'Videoaufnahmen mit Live-Effekten werden in diesem Browser nicht unterstützt.', recordingUnavailable: 'Videoaufnahme ist nicht verfügbar.', recordingFailed: 'Videoaufnahme fehlgeschlagen.', recordingStartFailed: 'Videoaufnahme konnte nicht gestartet werden.', searchFilters: 'Filter suchen', searchPlaceholder: 'Filter suchen', filterFamilies: 'Filterfamilien', all: 'Alle', favorites: 'Favoriten', recent: 'Zuletzt', favorite: '☆ Favorit', favoriteActive: '★ Favorit', reset: 'Filter zurücksetzen', savePreset: 'Voreinstellung speichern', presets: 'Voreinstellungen', deletePreset: 'Voreinstellung löschen', cameraFraming: 'Kamerabild', zoom: 'Zoom', mirrorOn: 'Spiegelung an', mirrorOff: 'Spiegelung aus', intensity: 'Intensität', aspectRatio: 'Aufnahmeformat', download: 'Ergebnis herunterladen', share: 'Ergebnis teilen', shareSetup: 'Filtereinstellungen teilen', shareSetupUnsupported: 'Das Teilen der Filtereinstellungen ist nicht verfügbar. Kopiere die aktuelle URL.', shareSetupFailed: 'Filtereinstellungen konnten nicht geteilt werden. Kopiere die aktuelle URL.', shareUnsupported: 'Teilen ist in diesem Browser nicht verfügbar. Ergebnis herunterladen.', shareFileUnsupported: 'Dieses Gerät kann diese Datei nicht teilen. Ergebnis herunterladen.', shareFailed: 'Teilen fehlgeschlagen. Ergebnis herunterladen.', family: { color: 'Farbe', mood: 'Stimmung', cinematic: 'Cine', mono: 'Mono', retro: 'Retro' } , ...FILTER_MASK_NEW_COPY.de },
  hi: { ...EN, selected: 'चयनित', startCamera: 'कैमरा शुरू करें', stop: 'रोकें', switchCamera: 'कैमरा बदलें', photo: 'फ़ोटो', recordVideo: 'वीडियो रिकॉर्ड करें', stopRecording: 'रिकॉर्डिंग रोकें', cameraUnavailable: 'इस ब्राउज़र में कैमरा उपलब्ध नहीं है।', cameraDenied: 'कैमरा या माइक्रोफ़ोन की अनुमति नहीं मिली या उपलब्ध नहीं है।', searchFilters: 'फ़िल्टर खोजें', searchPlaceholder: 'फ़िल्टर खोजें', filterFamilies: 'फ़िल्टर श्रेणियाँ', all: 'सभी', favorites: 'पसंदीदा', recent: 'हाल के', favorite: '☆ पसंदीदा', favoriteActive: '★ पसंदीदा', reset: 'फ़िल्टर रीसेट करें', savePreset: 'प्रीसेट सहेजें', presets: 'प्रीसेट', deletePreset: 'प्रीसेट हटाएँ', cameraFraming: 'कैमरा फ़्रेमिंग', zoom: 'ज़ूम', mirrorOn: 'मिरर चालू', mirrorOff: 'मिरर बंद', intensity: 'तीव्रता', aspectRatio: 'कैप्चर अनुपात', download: 'परिणाम डाउनलोड करें', share: 'परिणाम साझा करें', shareSetup: 'फ़िल्टर सेटिंग साझा करें', shareSetupUnsupported: 'फ़िल्टर सेटिंग साझा करना उपलब्ध नहीं है। वर्तमान URL कॉपी करें।', shareSetupFailed: 'फ़िल्टर सेटिंग साझा नहीं की जा सकी। वर्तमान URL कॉपी करें।', shareUnsupported: 'साझा करना उपलब्ध नहीं है। परिणाम डाउनलोड करें।', shareFileUnsupported: 'यह डिवाइस इस फ़ाइल को साझा नहीं कर सकता। परिणाम डाउनलोड करें।', shareFailed: 'साझा करना विफल रहा। परिणाम डाउनलोड करें।', family: { color: 'रंग', mood: 'मूड', cinematic: 'सिनेमैटिक', mono: 'मोनो', retro: 'रेट्रो' } , ...FILTER_MASK_NEW_COPY.hi },
  id: { ...EN, selected: 'Dipilih', startCamera: 'Mulai kamera', stop: 'Berhenti', switchCamera: 'Ganti kamera', photo: 'Foto', recordVideo: 'Rekam video', stopRecording: 'Hentikan rekaman', cameraUnavailable: 'Kamera tidak tersedia di browser ini.', cameraDenied: 'Akses kamera atau mikrofon ditolak atau tidak tersedia.', searchFilters: 'Cari filter', searchPlaceholder: 'Cari filter', filterFamilies: 'Keluarga filter', all: 'Semua', favorites: 'Favorit', recent: 'Terbaru', favorite: '☆ Favorit', favoriteActive: '★ Favorit', reset: 'Atur ulang filter', savePreset: 'Simpan preset', presets: 'Preset', deletePreset: 'Hapus preset', cameraFraming: 'Pembingkaian kamera', zoom: 'Zoom', mirrorOn: 'Cermin aktif', mirrorOff: 'Cermin nonaktif', intensity: 'Intensitas', aspectRatio: 'Rasio pengambilan', download: 'Unduh hasil', share: 'Bagikan hasil', shareSetup: 'Bagikan pengaturan filter', shareSetupUnsupported: 'Berbagi pengaturan filter tidak tersedia. Salin URL saat ini.', shareSetupFailed: 'Pengaturan filter tidak dapat dibagikan. Salin URL saat ini.', shareUnsupported: 'Berbagi tidak tersedia di browser ini. Gunakan Unduh hasil.', shareFileUnsupported: 'Perangkat ini tidak dapat membagikan file ini. Gunakan Unduh hasil.', shareFailed: 'Gagal membagikan. Gunakan Unduh hasil.', family: { color: 'Warna', mood: 'Suasana', cinematic: 'Sinematik', mono: 'Mono', retro: 'Retro' } , ...FILTER_MASK_NEW_COPY.id },
  it: { ...EN, selected: 'Selezionato', startCamera: 'Avvia fotocamera', stop: 'Ferma', switchCamera: 'Cambia fotocamera', photo: 'Foto', recordVideo: 'Registra video', stopRecording: 'Ferma registrazione', cameraUnavailable: 'La fotocamera non è disponibile in questo browser.', cameraDenied: 'Accesso a fotocamera o microfono negato o non disponibile.', searchFilters: 'Cerca filtri', searchPlaceholder: 'Cerca filtri', filterFamilies: 'Famiglie di filtri', all: 'Tutti', favorites: 'Preferiti', recent: 'Recenti', favorite: '☆ Preferito', favoriteActive: '★ Preferito', reset: 'Reimposta filtro', savePreset: 'Salva preset', presets: 'Preset', deletePreset: 'Elimina preset', cameraFraming: 'Inquadratura fotocamera', zoom: 'Zoom', mirrorOn: 'Specchio attivo', mirrorOff: 'Specchio disattivo', intensity: 'Intensità', aspectRatio: 'Formato di acquisizione', download: 'Scarica risultato', share: 'Condividi risultato', shareSetup: 'Condividi impostazioni filtro', shareSetupUnsupported: 'La condivisione delle impostazioni non è disponibile. Copia l’URL corrente.', shareSetupFailed: 'Impossibile condividere le impostazioni. Copia l’URL corrente.', shareUnsupported: 'Condivisione non disponibile. Usa Scarica risultato.', shareFileUnsupported: 'Questo dispositivo non può condividere il file. Usa Scarica risultato.', shareFailed: 'Condivisione non riuscita. Usa Scarica risultato.', family: { color: 'Colore', mood: 'Umore', cinematic: 'Cinematico', mono: 'Mono', retro: 'Retrò' } , ...FILTER_MASK_NEW_COPY.it },
  ja: { ...EN, selected: '選択中', startCamera: 'カメラを開始', stop: '停止', switchCamera: 'カメラを切り替え', photo: '写真', recordVideo: '動画を録画', stopRecording: '録画を停止', cameraUnavailable: 'このブラウザではカメラを利用できません。', cameraDenied: 'カメラまたはマイクへのアクセスが拒否されたか利用できません。', searchFilters: 'フィルターを検索', searchPlaceholder: 'フィルターを検索', filterFamilies: 'フィルター分類', all: 'すべて', favorites: 'お気に入り', recent: '最近', favorite: '☆ お気に入り', favoriteActive: '★ お気に入り', reset: 'フィルターをリセット', savePreset: 'プリセットを保存', presets: 'プリセット', deletePreset: 'プリセットを削除', cameraFraming: 'カメラのフレーミング', zoom: 'ズーム', mirrorOn: 'ミラーオン', mirrorOff: 'ミラーオフ', intensity: '強度', aspectRatio: '撮影比率', download: '結果をダウンロード', share: '結果を共有', shareSetup: 'フィルター設定を共有', shareSetupUnsupported: '設定の共有は利用できません。現在のURLをコピーしてください。', shareSetupFailed: '設定を共有できませんでした。現在のURLをコピーしてください。', shareUnsupported: '共有は利用できません。結果をダウンロードしてください。', shareFileUnsupported: 'このデバイスではこのファイルを共有できません。結果をダウンロードしてください。', shareFailed: '共有に失敗しました。結果をダウンロードしてください。', family: { color: 'カラー', mood: 'ムード', cinematic: 'シネマ', mono: 'モノ', retro: 'レトロ' } , ...FILTER_MASK_NEW_COPY.ja },
  ko: { ...EN, selected: '선택됨', startCamera: '카메라 시작', stop: '중지', switchCamera: '카메라 전환', photo: '사진', recordVideo: '동영상 녹화', stopRecording: '녹화 중지', cameraUnavailable: '이 브라우저에서는 카메라를 사용할 수 없습니다.', cameraDenied: '카메라 또는 마이크 권한이 거부되었거나 사용할 수 없습니다.', searchFilters: '필터 검색', searchPlaceholder: '필터 검색', filterFamilies: '필터 분류', all: '전체', favorites: '즐겨찾기', recent: '최근 항목', favorite: '☆ 즐겨찾기', favoriteActive: '★ 즐겨찾기', reset: '필터 초기화', savePreset: '프리셋 저장', presets: '프리셋', deletePreset: '프리셋 삭제', cameraFraming: '카메라 프레이밍', zoom: '확대', mirrorOn: '미러 켜짐', mirrorOff: '미러 꺼짐', intensity: '강도', aspectRatio: '촬영 비율', download: '결과 다운로드', share: '결과 공유', shareSetup: '필터 설정 공유', shareSetupUnsupported: '필터 설정 공유를 사용할 수 없습니다. 현재 URL을 복사하세요.', shareSetupFailed: '필터 설정을 공유하지 못했습니다. 현재 URL을 복사하세요.', shareUnsupported: '공유를 사용할 수 없습니다. 결과를 다운로드하세요.', shareFileUnsupported: '이 기기에서는 이 파일을 공유할 수 없습니다. 결과를 다운로드하세요.', shareFailed: '공유에 실패했습니다. 결과를 다운로드하세요.', family: { color: '색상', mood: '무드', cinematic: '시네마틱', mono: '모노', retro: '레트로' } , ...FILTER_MASK_NEW_COPY.ko },
  ms: { ...EN, selected: 'Dipilih', startCamera: 'Mulakan kamera', stop: 'Berhenti', switchCamera: 'Tukar kamera', photo: 'Foto', recordVideo: 'Rakam video', stopRecording: 'Hentikan rakaman', cameraUnavailable: 'Kamera tidak tersedia dalam pelayar ini.', cameraDenied: 'Akses kamera atau mikrofon ditolak atau tidak tersedia.', searchFilters: 'Cari penapis', searchPlaceholder: 'Cari penapis', filterFamilies: 'Kumpulan penapis', all: 'Semua', favorites: 'Kegemaran', recent: 'Terkini', favorite: '☆ Kegemaran', favoriteActive: '★ Kegemaran', reset: 'Tetapkan semula penapis', savePreset: 'Simpan pratetap', presets: 'Pratetap', deletePreset: 'Padam pratetap', cameraFraming: 'Pembingkaian kamera', zoom: 'Zum', mirrorOn: 'Cermin aktif', mirrorOff: 'Cermin tidak aktif', intensity: 'Intensiti', aspectRatio: 'Nisbah tangkapan', download: 'Muat turun hasil', share: 'Kongsi hasil', shareSetup: 'Kongsi tetapan penapis', shareSetupUnsupported: 'Perkongsian tetapan penapis tidak tersedia. Salin URL semasa.', shareSetupFailed: 'Tetapan penapis tidak dapat dikongsi. Salin URL semasa.', shareUnsupported: 'Perkongsian tidak tersedia. Gunakan Muat turun hasil.', shareFileUnsupported: 'Peranti ini tidak boleh berkongsi fail ini. Gunakan Muat turun hasil.', shareFailed: 'Perkongsian gagal. Gunakan Muat turun hasil.', family: { color: 'Warna', mood: 'Suasana', cinematic: 'Sinematik', mono: 'Mono', retro: 'Retro' } , ...FILTER_MASK_NEW_COPY.ms },
  nl: { ...EN, selected: 'Geselecteerd', startCamera: 'Camera starten', stop: 'Stoppen', switchCamera: 'Camera wisselen', photo: 'Foto', recordVideo: 'Video opnemen', stopRecording: 'Opname stoppen', cameraUnavailable: 'Camera is niet beschikbaar in deze browser.', cameraDenied: 'Toegang tot camera of microfoon is geweigerd of niet beschikbaar.', searchFilters: 'Filters zoeken', searchPlaceholder: 'Filters zoeken', filterFamilies: 'Filterfamilies', all: 'Alle', favorites: 'Favorieten', recent: 'Recent', favorite: '☆ Favoriet', favoriteActive: '★ Favoriet', reset: 'Filter resetten', savePreset: 'Voorinstelling opslaan', presets: 'Voorinstellingen', deletePreset: 'Voorinstelling verwijderen', cameraFraming: 'Camerakadrering', zoom: 'Zoom', mirrorOn: 'Spiegel aan', mirrorOff: 'Spiegel uit', intensity: 'Intensiteit', aspectRatio: 'Opnameverhouding', download: 'Resultaat downloaden', share: 'Resultaat delen', shareSetup: 'Filterinstellingen delen', shareSetupUnsupported: 'Het delen van filterinstellingen is niet beschikbaar. Kopieer de huidige URL.', shareSetupFailed: 'Filterinstellingen konden niet worden gedeeld. Kopieer de huidige URL.', shareUnsupported: 'Delen is niet beschikbaar. Gebruik Resultaat downloaden.', shareFileUnsupported: 'Dit apparaat kan dit bestand niet delen. Gebruik Resultaat downloaden.', shareFailed: 'Delen mislukt. Gebruik Resultaat downloaden.', family: { color: 'Kleur', mood: 'Sfeer', cinematic: 'Cinematisch', mono: 'Mono', retro: 'Retro' } , ...FILTER_MASK_NEW_COPY.nl },
  pl: { ...EN, selected: 'Wybrano', startCamera: 'Uruchom aparat', stop: 'Zatrzymaj', switchCamera: 'Przełącz aparat', photo: 'Zdjęcie', recordVideo: 'Nagraj wideo', stopRecording: 'Zatrzymaj nagrywanie', cameraUnavailable: 'Aparat nie jest dostępny w tej przeglądarce.', cameraDenied: 'Odmówiono dostępu do aparatu lub mikrofonu albo są one niedostępne.', searchFilters: 'Szukaj filtrów', searchPlaceholder: 'Szukaj filtrów', filterFamilies: 'Rodziny filtrów', all: 'Wszystkie', favorites: 'Ulubione', recent: 'Ostatnie', favorite: '☆ Ulubione', favoriteActive: '★ Ulubione', reset: 'Resetuj filtr', savePreset: 'Zapisz preset', presets: 'Presety', deletePreset: 'Usuń preset', cameraFraming: 'Kadrowanie aparatu', zoom: 'Zoom', mirrorOn: 'Lustro włączone', mirrorOff: 'Lustro wyłączone', intensity: 'Intensywność', aspectRatio: 'Proporcje ujęcia', download: 'Pobierz wynik', share: 'Udostępnij wynik', shareSetup: 'Udostępnij ustawienia filtra', shareSetupUnsupported: 'Udostępnianie ustawień filtra jest niedostępne. Skopiuj bieżący URL.', shareSetupFailed: 'Nie udało się udostępnić ustawień filtra. Skopiuj bieżący URL.', shareUnsupported: 'Udostępnianie jest niedostępne. Użyj Pobierz wynik.', shareFileUnsupported: 'To urządzenie nie może udostępnić tego pliku. Użyj Pobierz wynik.', shareFailed: 'Udostępnianie nie powiodło się. Użyj Pobierz wynik.', family: { color: 'Kolor', mood: 'Nastrój', cinematic: 'Kino', mono: 'Mono', retro: 'Retro' } , ...FILTER_MASK_NEW_COPY.pl },
  pt: { ...EN, selected: 'Selecionado', startCamera: 'Iniciar câmera', stop: 'Parar', switchCamera: 'Trocar câmera', photo: 'Foto', recordVideo: 'Gravar vídeo', stopRecording: 'Parar gravação', cameraUnavailable: 'A câmera não está disponível neste navegador.', cameraDenied: 'O acesso à câmera ou ao microfone foi negado ou não está disponível.', searchFilters: 'Pesquisar filtros', searchPlaceholder: 'Pesquisar filtros', filterFamilies: 'Famílias de filtros', all: 'Todos', favorites: 'Favoritos', recent: 'Recentes', favorite: '☆ Favorito', favoriteActive: '★ Favorito', reset: 'Redefinir filtro', savePreset: 'Salvar predefinição', presets: 'Predefinições', deletePreset: 'Excluir predefinição', cameraFraming: 'Enquadramento da câmera', zoom: 'Zoom', mirrorOn: 'Espelho ativado', mirrorOff: 'Espelho desativado', intensity: 'Intensidade', aspectRatio: 'Proporção de captura', download: 'Baixar resultado', share: 'Compartilhar resultado', shareSetup: 'Compartilhar configuração', shareSetupUnsupported: 'O compartilhamento da configuração não está disponível. Copie a URL atual.', shareSetupFailed: 'Não foi possível compartilhar a configuração. Copie a URL atual.', shareUnsupported: 'O compartilhamento não está disponível. Use Baixar resultado.', shareFileUnsupported: 'Este dispositivo não pode compartilhar este arquivo. Use Baixar resultado.', shareFailed: 'Falha ao compartilhar. Use Baixar resultado.', family: { color: 'Cor', mood: 'Clima', cinematic: 'Cinemático', mono: 'Mono', retro: 'Retrô' } , ...FILTER_MASK_NEW_COPY.pt },
  ru: { ...EN, selected: 'Выбрано', startCamera: 'Запустить камеру', stop: 'Остановить', switchCamera: 'Сменить камеру', photo: 'Фото', recordVideo: 'Записать видео', stopRecording: 'Остановить запись', cameraUnavailable: 'Камера недоступна в этом браузере.', cameraDenied: 'Доступ к камере или микрофону запрещён или недоступен.', searchFilters: 'Поиск фильтров', searchPlaceholder: 'Поиск фильтров', filterFamilies: 'Категории фильтров', all: 'Все', favorites: 'Избранное', recent: 'Недавние', favorite: '☆ Избранное', favoriteActive: '★ Избранное', reset: 'Сбросить фильтр', savePreset: 'Сохранить пресет', presets: 'Пресеты', deletePreset: 'Удалить пресет', cameraFraming: 'Кадрирование камеры', zoom: 'Масштаб', mirrorOn: 'Зеркало включено', mirrorOff: 'Зеркало выключено', intensity: 'Интенсивность', aspectRatio: 'Соотношение кадра', download: 'Скачать результат', share: 'Поделиться результатом', shareSetup: 'Поделиться настройкой фильтра', shareSetupUnsupported: 'Общий доступ к настройке недоступен. Скопируйте текущий URL.', shareSetupFailed: 'Не удалось поделиться настройкой. Скопируйте текущий URL.', shareUnsupported: 'Общий доступ недоступен. Используйте Скачать результат.', shareFileUnsupported: 'Это устройство не может поделиться этим файлом. Используйте Скачать результат.', shareFailed: 'Не удалось поделиться. Используйте Скачать результат.', family: { color: 'Цвет', mood: 'Настроение', cinematic: 'Кино', mono: 'Моно', retro: 'Ретро' } , ...FILTER_MASK_NEW_COPY.ru },
  sv: { ...EN, selected: 'Vald', startCamera: 'Starta kamera', stop: 'Stoppa', switchCamera: 'Byt kamera', photo: 'Foto', recordVideo: 'Spela in video', stopRecording: 'Stoppa inspelning', cameraUnavailable: 'Kameran är inte tillgänglig i den här webbläsaren.', cameraDenied: 'Åtkomst till kamera eller mikrofon nekades eller är inte tillgänglig.', searchFilters: 'Sök filter', searchPlaceholder: 'Sök filter', filterFamilies: 'Filterfamiljer', all: 'Alla', favorites: 'Favoriter', recent: 'Senaste', favorite: '☆ Favorit', favoriteActive: '★ Favorit', reset: 'Återställ filter', savePreset: 'Spara förinställning', presets: 'Förinställningar', deletePreset: 'Ta bort förinställning', cameraFraming: 'Kamerainramning', zoom: 'Zoom', mirrorOn: 'Spegel på', mirrorOff: 'Spegel av', intensity: 'Intensitet', aspectRatio: 'Bildformat', download: 'Ladda ned resultat', share: 'Dela resultat', shareSetup: 'Dela filterinställning', shareSetupUnsupported: 'Det går inte att dela filterinställningen. Kopiera den aktuella URL:en.', shareSetupFailed: 'Filterinställningen kunde inte delas. Kopiera den aktuella URL:en.', shareUnsupported: 'Delning är inte tillgänglig. Använd Ladda ned resultat.', shareFileUnsupported: 'Den här enheten kan inte dela filen. Använd Ladda ned resultat.', shareFailed: 'Delning misslyckades. Använd Ladda ned resultat.', family: { color: 'Färg', mood: 'Stämning', cinematic: 'Cinematisk', mono: 'Mono', retro: 'Retro' } , ...FILTER_MASK_NEW_COPY.sv },
  th: { ...EN, selected: 'เลือกแล้ว', startCamera: 'เริ่มกล้อง', stop: 'หยุด', switchCamera: 'สลับกล้อง', photo: 'ถ่ายภาพ', recordVideo: 'บันทึกวิดีโอ', stopRecording: 'หยุดการบันทึก', cameraUnavailable: 'กล้องไม่พร้อมใช้งานในเบราว์เซอร์นี้', cameraDenied: 'ไม่อนุญาตให้เข้าถึงกล้องหรือไมโครโฟน หรือไม่พร้อมใช้งาน', searchFilters: 'ค้นหาฟิลเตอร์', searchPlaceholder: 'ค้นหาฟิลเตอร์', filterFamilies: 'หมวดฟิลเตอร์', all: 'ทั้งหมด', favorites: 'รายการโปรด', recent: 'ล่าสุด', favorite: '☆ รายการโปรด', favoriteActive: '★ รายการโปรด', reset: 'รีเซ็ตฟิลเตอร์', savePreset: 'บันทึกพรีเซ็ต', presets: 'พรีเซ็ต', deletePreset: 'ลบพรีเซ็ต', cameraFraming: 'การจัดเฟรมกล้อง', zoom: 'ซูม', mirrorOn: 'เปิดมิเรอร์', mirrorOff: 'ปิดมิเรอร์', intensity: 'ความเข้ม', aspectRatio: 'อัตราส่วนการถ่าย', download: 'ดาวน์โหลดผลลัพธ์', share: 'แชร์ผลลัพธ์', shareSetup: 'แชร์การตั้งค่าฟิลเตอร์', shareSetupUnsupported: 'ไม่รองรับการแชร์การตั้งค่า โปรดคัดลอก URL ปัจจุบัน', shareSetupFailed: 'ไม่สามารถแชร์การตั้งค่าได้ โปรดคัดลอก URL ปัจจุบัน', shareUnsupported: 'ไม่รองรับการแชร์ ใช้ดาวน์โหลดผลลัพธ์แทน', shareFileUnsupported: 'อุปกรณ์นี้แชร์ไฟล์นี้ไม่ได้ ใช้ดาวน์โหลดผลลัพธ์แทน', shareFailed: 'แชร์ไม่สำเร็จ ใช้ดาวน์โหลดผลลัพธ์แทน', family: { color: 'สี', mood: 'อารมณ์', cinematic: 'ภาพยนตร์', mono: 'โมโน', retro: 'เรโทร' } , ...FILTER_MASK_NEW_COPY.th },
  tr: { ...EN, selected: 'Seçili', startCamera: 'Kamerayı başlat', stop: 'Durdur', switchCamera: 'Kamerayı değiştir', photo: 'Fotoğraf', recordVideo: 'Video kaydet', stopRecording: 'Kaydı durdur', cameraUnavailable: 'Kamera bu tarayıcıda kullanılamıyor.', cameraDenied: 'Kamera veya mikrofon erişimi reddedildi ya da kullanılamıyor.', searchFilters: 'Filtreleri ara', searchPlaceholder: 'Filtreleri ara', filterFamilies: 'Filtre grupları', all: 'Tümü', favorites: 'Favoriler', recent: 'Son kullanılanlar', favorite: '☆ Favori', favoriteActive: '★ Favori', reset: 'Filtreyi sıfırla', savePreset: 'Ön ayarı kaydet', presets: 'Ön ayarlar', deletePreset: 'Ön ayarı sil', cameraFraming: 'Kamera kadrajı', zoom: 'Yakınlaştırma', mirrorOn: 'Ayna açık', mirrorOff: 'Ayna kapalı', intensity: 'Yoğunluk', aspectRatio: 'Çekim oranı', download: 'Sonucu indir', share: 'Sonucu paylaş', shareSetup: 'Filtre ayarını paylaş', shareSetupUnsupported: 'Filtre ayarı paylaşımı kullanılamıyor. Geçerli URL\'yi kopyalayın.', shareSetupFailed: 'Filtre ayarı paylaşılamadı. Geçerli URL\'yi kopyalayın.', shareUnsupported: 'Paylaşım bu tarayıcıda kullanılamıyor. Sonucu indirin.', shareFileUnsupported: 'Bu cihaz bu dosyayı paylaşamıyor. Sonucu indirin.', shareFailed: 'Paylaşım başarısız. Sonucu indirin.', family: { color: 'Renk', mood: 'Mod', cinematic: 'Sinematik', mono: 'Mono', retro: 'Retro' } , ...FILTER_MASK_NEW_COPY.tr },
  uk: { ...EN, selected: 'Вибрано', startCamera: 'Запустити камеру', stop: 'Зупинити', switchCamera: 'Перемкнути камеру', photo: 'Фото', recordVideo: 'Записати відео', stopRecording: 'Зупинити запис', cameraUnavailable: 'Камера недоступна в цьому браузері.', cameraDenied: 'Доступ до камери або мікрофона заборонено або вони недоступні.', searchFilters: 'Пошук фільтрів', searchPlaceholder: 'Пошук фільтрів', filterFamilies: 'Категорії фільтрів', all: 'Усі', favorites: 'Уподобані', recent: 'Нещодавні', favorite: '☆ Уподобане', favoriteActive: '★ Уподобане', reset: 'Скинути фільтр', savePreset: 'Зберегти пресет', presets: 'Пресети', deletePreset: 'Видалити пресет', cameraFraming: 'Кадрування камери', zoom: 'Масштаб', mirrorOn: 'Дзеркало увімкнено', mirrorOff: 'Дзеркало вимкнено', intensity: 'Інтенсивність', aspectRatio: 'Співвідношення кадру', download: 'Завантажити результат', share: 'Поділитися результатом', shareSetup: 'Поділитися налаштуванням фільтра', shareSetupUnsupported: 'Спільний доступ до налаштування недоступний. Скопіюйте поточний URL.', shareSetupFailed: 'Не вдалося поділитися налаштуванням. Скопіюйте поточний URL.', shareUnsupported: 'Спільний доступ недоступний. Використайте Завантажити результат.', shareFileUnsupported: 'Цей пристрій не може поділитися цим файлом. Використайте Завантажити результат.', shareFailed: 'Не вдалося поділитися. Використайте Завантажити результат.', family: { color: 'Колір', mood: 'Настрій', cinematic: 'Кінематографічний', mono: 'Моно', retro: 'Ретро' } , ...FILTER_MASK_NEW_COPY.uk },
  vi: { ...EN, selected: 'Đã chọn', startCamera: 'Bật camera', stop: 'Dừng', switchCamera: 'Đổi camera', photo: 'Ảnh', recordVideo: 'Quay video', stopRecording: 'Dừng quay', cameraUnavailable: 'Camera không khả dụng trong trình duyệt này.', cameraDenied: 'Quyền truy cập camera hoặc mic bị từ chối hoặc không khả dụng.', searchFilters: 'Tìm bộ lọc', searchPlaceholder: 'Tìm bộ lọc', filterFamilies: 'Nhóm bộ lọc', all: 'Tất cả', favorites: 'Yêu thích', recent: 'Gần đây', favorite: '☆ Yêu thích', favoriteActive: '★ Yêu thích', reset: 'Đặt lại bộ lọc', savePreset: 'Lưu cài đặt', presets: 'Cài đặt', deletePreset: 'Xóa cài đặt', cameraFraming: 'Khung hình camera', zoom: 'Thu phóng', mirrorOn: 'Bật gương', mirrorOff: 'Tắt gương', intensity: 'Cường độ', aspectRatio: 'Tỷ lệ khung hình', download: 'Tải kết quả', share: 'Chia sẻ kết quả', shareSetup: 'Chia sẻ cài đặt bộ lọc', shareSetupUnsupported: 'Không hỗ trợ chia sẻ cài đặt. Hãy sao chép URL hiện tại.', shareSetupFailed: 'Không thể chia sẻ cài đặt. Hãy sao chép URL hiện tại.', shareUnsupported: 'Không hỗ trợ chia sẻ. Hãy dùng Tải kết quả.', shareFileUnsupported: 'Thiết bị này không thể chia sẻ tệp. Hãy dùng Tải kết quả.', shareFailed: 'Chia sẻ thất bại. Hãy dùng Tải kết quả.', family: { color: 'Màu', mood: 'Tâm trạng', cinematic: 'Điện ảnh', mono: 'Mono', retro: 'Retro' } , ...FILTER_MASK_NEW_COPY.vi },
};
