import type { Locale } from './config';

type SharedCopy = Readonly<{
  processing: string;
  inputs: string;
  browserSuffix: string;
  externalSuffix: string;
  chooseFile: string;
  optional: string;
  originalText: string;
  modifiedText: string;
  regexPattern: string;
  regexInput: string;
  topText: string;
  bottomText: string;
  watermarkText: string;
  foregroundColor: string;
  backgroundColor: string;
  generateQr: string;
  chooseQrImage: string;
  exportClip: string;
  compressImage: string;
  compressAllZip: string;
}>;

export const SHARED_TOOL_UI_COPY: Record<string, SharedCopy> = {
  ar: { processing: 'معالجة محلية', inputs: 'المدخلات', browserSuffix: 'تُعالج في متصفحك عندما تدعم الأداة ذلك.', externalSuffix: 'تستخدم نقطة معالجة خارجية مُهيأة ولا تُقدَّم على أنها محلية فقط.', chooseFile: 'اختر ملفًا', optional: 'اختياري', originalText: 'النص الأصلي', modifiedText: 'النص المعدّل', regexPattern: 'نمط Regex', regexInput: 'إدخال Regex', topText: 'النص العلوي', bottomText: 'النص السفلي', watermarkText: 'نص العلامة المائية', foregroundColor: 'لون المقدمة', backgroundColor: 'لون الخلفية', generateQr: 'إنشاء QR', chooseQrImage: 'اختر صورة QR', exportClip: 'تصدير المقطع', compressImage: 'ضغط الصورة', compressAllZip: 'ضغط الكل إلى ZIP' },
  en: { processing: 'Local processing', inputs: 'Inputs', browserSuffix: 'are processed in your browser when supported by the tool.', externalSuffix: 'uses a configured external processing endpoint and is not presented as local-only.', chooseFile: 'Choose a file', optional: 'Optional', originalText: 'Original text', modifiedText: 'Modified text', regexPattern: 'Regex pattern', regexInput: 'Regex input', topText: 'Top text', bottomText: 'Bottom text', watermarkText: 'Watermark text', foregroundColor: 'Foreground color', backgroundColor: 'Background color', generateQr: 'Generate QR', chooseQrImage: 'Choose QR image', exportClip: 'Export clip', compressImage: 'Compress image', compressAllZip: 'Compress all to ZIP' },
  es: { processing: 'Procesamiento local', inputs: 'Entradas', browserSuffix: 'se procesan en tu navegador cuando la herramienta lo admite.', externalSuffix: 'usa un punto de procesamiento externo configurado y no se presenta como local.', chooseFile: 'Elige un archivo', optional: 'Opcional', originalText: 'Texto original', modifiedText: 'Texto modificado', regexPattern: 'Patrón Regex', regexInput: 'Entrada Regex', topText: 'Texto superior', bottomText: 'Texto inferior', watermarkText: 'Texto de marca de agua', foregroundColor: 'Color de primer plano', backgroundColor: 'Color de fondo', generateQr: 'Generar QR', chooseQrImage: 'Elige una imagen QR', exportClip: 'Exportar clip', compressImage: 'Comprimir imagen', compressAllZip: 'Comprimir todo en ZIP' },
  fr: { processing: 'Traitement local', inputs: 'Entrées', browserSuffix: 'sont traitées dans votre navigateur lorsque l’outil le permet.', externalSuffix: 'utilise un point de traitement externe configuré et n’est pas présenté comme local.', chooseFile: 'Choisissez un fichier', optional: 'Facultatif', originalText: 'Texte original', modifiedText: 'Texte modifié', regexPattern: 'Motif Regex', regexInput: 'Entrée Regex', topText: 'Texte supérieur', bottomText: 'Texte inférieur', watermarkText: 'Texte du filigrane', foregroundColor: 'Couleur de premier plan', backgroundColor: 'Couleur d’arrière-plan', generateQr: 'Générer un QR', chooseQrImage: 'Choisissez une image QR', exportClip: 'Exporter le clip', compressImage: 'Compresser l’image', compressAllZip: 'Tout compresser en ZIP' },
  de: { processing: 'Lokale Verarbeitung', inputs: 'Eingaben', browserSuffix: 'werden in deinem Browser verarbeitet, wenn das Tool dies unterstützt.', externalSuffix: 'verwendet einen konfigurierten externen Endpunkt und wird nicht als rein lokal dargestellt.', chooseFile: 'Datei auswählen', optional: 'Optional', originalText: 'Originaltext', modifiedText: 'Geänderter Text', regexPattern: 'Regex-Muster', regexInput: 'Regex-Eingabe', topText: 'Oberer Text', bottomText: 'Unterer Text', watermarkText: 'Wasserzeichentext', foregroundColor: 'Vordergrundfarbe', backgroundColor: 'Hintergrundfarbe', generateQr: 'QR generieren', chooseQrImage: 'QR-Bild auswählen', exportClip: 'Clip exportieren', compressImage: 'Bild komprimieren', compressAllZip: 'Alle zu ZIP komprimieren' },
  ru: { processing: 'Локальная обработка', inputs: 'Входные данные', browserSuffix: 'обрабатываются в браузере, если инструмент это поддерживает.', externalSuffix: 'использует настроенную внешнюю точку обработки и не позиционируется как полностью локальный.', chooseFile: 'Выберите файл', optional: 'Необязательно', originalText: 'Исходный текст', modifiedText: 'Изменённый текст', regexPattern: 'Шаблон Regex', regexInput: 'Ввод Regex', topText: 'Верхний текст', bottomText: 'Нижний текст', watermarkText: 'Текст водяного знака', foregroundColor: 'Цвет переднего плана', backgroundColor: 'Цвет фона', generateQr: 'Создать QR', chooseQrImage: 'Выберите изображение QR', exportClip: 'Экспортировать фрагмент', compressImage: 'Сжать изображение', compressAllZip: 'Сжать всё в ZIP' },
  zh: { processing: '本地处理', inputs: '输入', browserSuffix: '在工具支持时会在你的浏览器中处理。', externalSuffix: '使用已配置的外部处理端点，并不会标记为仅本地处理。', chooseFile: '选择文件', optional: '可选', originalText: '原始文本', modifiedText: '修改后的文本', regexPattern: '正则表达式模式', regexInput: '正则输入', topText: '顶部文本', bottomText: '底部文本', watermarkText: '水印文字', foregroundColor: '前景色', backgroundColor: '背景色', generateQr: '生成二维码', chooseQrImage: '选择二维码图片', exportClip: '导出片段', compressImage: '压缩图片', compressAllZip: '全部压缩为 ZIP' },
  hi: { processing: 'स्थानीय प्रोसेसिंग', inputs: 'इनपुट', browserSuffix: 'टूल के समर्थन पर आपके ब्राउज़र में संसाधित होते हैं।', externalSuffix: 'कॉन्फ़िगर किए गए बाहरी प्रोसेसिंग एंडपॉइंट का उपयोग करता है और इसे केवल स्थानीय के रूप में प्रस्तुत नहीं किया जाता।', chooseFile: 'फ़ाइल चुनें', optional: 'वैकल्पिक', originalText: 'मूल टेक्स्ट', modifiedText: 'संशोधित टेक्स्ट', regexPattern: 'Regex पैटर्न', regexInput: 'Regex इनपुट', topText: 'ऊपरी टेक्स्ट', bottomText: 'निचला टेक्स्ट', watermarkText: 'वॉटरमार्क टेक्स्ट', foregroundColor: 'अग्रभूमि रंग', backgroundColor: 'पृष्ठभूमि रंग', generateQr: 'QR बनाएं', chooseQrImage: 'QR छवि चुनें', exportClip: 'क्लिप निर्यात करें', compressImage: 'छवि संपीड़ित करें', compressAllZip: 'सभी को ZIP में संपीड़ित करें' },
  id: { processing: 'Pemrosesan lokal', inputs: 'Input', browserSuffix: 'diproses di browser Anda jika alat mendukungnya.', externalSuffix: 'menggunakan endpoint pemrosesan eksternal yang dikonfigurasi dan tidak disajikan sebagai lokal saja.', chooseFile: 'Pilih file', optional: 'Opsional', originalText: 'Teks asli', modifiedText: 'Teks yang diubah', regexPattern: 'Pola Regex', regexInput: 'Input Regex', topText: 'Teks atas', bottomText: 'Teks bawah', watermarkText: 'Teks tanda air', foregroundColor: 'Warna latar depan', backgroundColor: 'Warna latar belakang', generateQr: 'Buat QR', chooseQrImage: 'Pilih gambar QR', exportClip: 'Ekspor klip', compressImage: 'Kompres gambar', compressAllZip: 'Kompres semua ke ZIP' },
  ur: { processing: 'مقامی پروسیسنگ', inputs: 'ان پٹ', browserSuffix: 'ٹول کی معاونت ہونے پر آپ کے براؤزر میں پراسیس ہوتے ہیں۔', externalSuffix: 'مخصوص بیرونی پروسیسنگ اینڈ پوائنٹ استعمال کرتا ہے اور اسے صرف مقامی کے طور پر پیش نہیں کیا جاتا۔', chooseFile: 'فائل منتخب کریں', optional: 'اختیاری', originalText: 'اصل متن', modifiedText: 'ترمیم شدہ متن', regexPattern: 'Regex پیٹرن', regexInput: 'Regex ان پٹ', topText: 'اوپری متن', bottomText: 'نچلا متن', watermarkText: 'واٹر مارک متن', foregroundColor: 'پیش منظر کا رنگ', backgroundColor: 'پس منظر کا رنگ', generateQr: 'QR بنائیں', chooseQrImage: 'QR تصویر منتخب کریں', exportClip: 'کلپ برآمد کریں', compressImage: 'تصویر کمپریس کریں', compressAllZip: 'سب کو ZIP میں کمپریس کریں' },
  ja: { processing: 'ローカル処理', inputs: '入力', browserSuffix: 'ツールが対応している場合はブラウザ内で処理されます。', externalSuffix: '設定済みの外部処理エンドポイントを使用し、完全なローカル処理としては表示されません。', chooseFile: 'ファイルを選択', optional: '任意', originalText: '元のテキスト', modifiedText: '変更後のテキスト', regexPattern: '正規表現パターン', regexInput: '正規表現入力', topText: '上部テキスト', bottomText: '下部テキスト', watermarkText: '透かしテキスト', foregroundColor: '前景色', backgroundColor: '背景色', generateQr: 'QRを生成', chooseQrImage: 'QR画像を選択', exportClip: 'クリップを書き出す', compressImage: '画像を圧縮', compressAllZip: 'すべてをZIPに圧縮' },
  pt: { processing: 'Processamento local', inputs: 'Entradas', browserSuffix: 'são processadas no seu navegador quando a ferramenta oferece suporte.', externalSuffix: 'usa um endpoint externo configurado e não é apresentada como apenas local.', chooseFile: 'Escolha um arquivo', optional: 'Opcional', originalText: 'Texto original', modifiedText: 'Texto modificado', regexPattern: 'Padrão Regex', regexInput: 'Entrada Regex', topText: 'Texto superior', bottomText: 'Texto inferior', watermarkText: 'Texto da marca d’água', foregroundColor: 'Cor do primeiro plano', backgroundColor: 'Cor do plano de fundo', generateQr: 'Gerar QR', chooseQrImage: 'Escolha uma imagem QR', exportClip: 'Exportar clipe', compressImage: 'Comprimir imagem', compressAllZip: 'Comprimir tudo em ZIP' },
  it: { processing: 'Elaborazione locale', inputs: 'Input', browserSuffix: 'vengono elaborati nel browser quando lo strumento lo supporta.', externalSuffix: 'usa un endpoint di elaborazione esterno configurato e non viene presentato come esclusivamente locale.', chooseFile: 'Scegli un file', optional: 'Facoltativo', originalText: 'Testo originale', modifiedText: 'Testo modificato', regexPattern: 'Pattern Regex', regexInput: 'Input Regex', topText: 'Testo superiore', bottomText: 'Testo inferiore', watermarkText: 'Testo filigrana', foregroundColor: 'Colore di primo piano', backgroundColor: 'Colore di sfondo', generateQr: 'Genera QR', chooseQrImage: 'Scegli immagine QR', exportClip: 'Esporta clip', compressImage: 'Comprimi immagine', compressAllZip: 'Comprimi tutto in ZIP' },
  ko: { processing: '로컬 처리', inputs: '입력', browserSuffix: '도구가 지원하는 경우 브라우저에서 처리됩니다.', externalSuffix: '구성된 외부 처리 엔드포인트를 사용하며 완전한 로컬 처리로 표시되지 않습니다.', chooseFile: '파일 선택', optional: '선택 사항', originalText: '원본 텍스트', modifiedText: '수정된 텍스트', regexPattern: '정규식 패턴', regexInput: '정규식 입력', topText: '위쪽 텍스트', bottomText: '아래쪽 텍스트', watermarkText: '워터마크 텍스트', foregroundColor: '전경색', backgroundColor: '배경색', generateQr: 'QR 생성', chooseQrImage: 'QR 이미지 선택', exportClip: '클립 내보내기', compressImage: '이미지 압축', compressAllZip: '모두 ZIP으로 압축' },
  nl: { processing: 'Lokale verwerking', inputs: 'Invoer', browserSuffix: 'worden in je browser verwerkt wanneer de tool dit ondersteunt.', externalSuffix: 'gebruikt een geconfigureerd extern verwerkingseindpunt en wordt niet als alleen-lokaal gepresenteerd.', chooseFile: 'Kies een bestand', optional: 'Optioneel', originalText: 'Oorspronkelijke tekst', modifiedText: 'Aangepaste tekst', regexPattern: 'Regex-patroon', regexInput: 'Regex-invoer', topText: 'Bovenste tekst', bottomText: 'Onderste tekst', watermarkText: 'Watermerktekst', foregroundColor: 'Voorgrondkleur', backgroundColor: 'Achtergrondkleur', generateQr: 'QR genereren', chooseQrImage: 'Kies QR-afbeelding', exportClip: 'Clip exporteren', compressImage: 'Afbeelding comprimeren', compressAllZip: 'Alles naar ZIP comprimeren' },
  pl: { processing: 'Przetwarzanie lokalne', inputs: 'Wejścia', browserSuffix: 'są przetwarzane w przeglądarce, jeśli narzędzie to obsługuje.', externalSuffix: 'używa skonfigurowanego zewnętrznego punktu przetwarzania i nie jest przedstawiane jako wyłącznie lokalne.', chooseFile: 'Wybierz plik', optional: 'Opcjonalnie', originalText: 'Tekst oryginalny', modifiedText: 'Zmodyfikowany tekst', regexPattern: 'Wzorzec Regex', regexInput: 'Wejście Regex', topText: 'Górny tekst', bottomText: 'Dolny tekst', watermarkText: 'Tekst znaku wodnego', foregroundColor: 'Kolor pierwszego planu', backgroundColor: 'Kolor tła', generateQr: 'Generuj QR', chooseQrImage: 'Wybierz obraz QR', exportClip: 'Eksportuj klip', compressImage: 'Kompresuj obraz', compressAllZip: 'Kompresuj wszystko do ZIP' },
  tr: { processing: 'Yerel işleme', inputs: 'Girdiler', browserSuffix: 'araç desteklediğinde tarayıcınızda işlenir.', externalSuffix: 'yapılandırılmış bir harici işleme uç noktası kullanır ve yalnızca yerel olarak sunulmaz.', chooseFile: 'Dosya seçin', optional: 'İsteğe bağlı', originalText: 'Orijinal metin', modifiedText: 'Değiştirilmiş metin', regexPattern: 'Regex deseni', regexInput: 'Regex girişi', topText: 'Üst metin', bottomText: 'Alt metin', watermarkText: 'Filigran metni', foregroundColor: 'Ön plan rengi', backgroundColor: 'Arka plan rengi', generateQr: 'QR oluştur', chooseQrImage: 'QR görseli seçin', exportClip: 'Klibi dışa aktar', compressImage: 'Görseli sıkıştır', compressAllZip: 'Tümünü ZIP olarak sıkıştır' },
  vi: { processing: 'Xử lý cục bộ', inputs: 'Đầu vào', browserSuffix: 'được xử lý trong trình duyệt khi công cụ hỗ trợ.', externalSuffix: 'sử dụng điểm cuối xử lý bên ngoài đã cấu hình và không được trình bày là chỉ xử lý cục bộ.', chooseFile: 'Chọn tệp', optional: 'Tùy chọn', originalText: 'Văn bản gốc', modifiedText: 'Văn bản đã sửa', regexPattern: 'Mẫu Regex', regexInput: 'Đầu vào Regex', topText: 'Văn bản trên', bottomText: 'Văn bản dưới', watermarkText: 'Văn bản hình mờ', foregroundColor: 'Màu tiền cảnh', backgroundColor: 'Màu nền', generateQr: 'Tạo QR', chooseQrImage: 'Chọn ảnh QR', exportClip: 'Xuất clip', compressImage: 'Nén ảnh', compressAllZip: 'Nén tất cả thành ZIP' },
  th: { processing: 'การประมวลผลภายในเครื่อง', inputs: 'อินพุต', browserSuffix: 'จะประมวลผลในเบราว์เซอร์ของคุณเมื่อเครื่องมือรองรับ', externalSuffix: 'ใช้ปลายทางการประมวลผลภายนอกที่กำหนดค่าไว้และจะไม่แสดงว่าเป็นการประมวลผลภายในเครื่องเท่านั้น', chooseFile: 'เลือกไฟล์', optional: 'ไม่บังคับ', originalText: 'ข้อความต้นฉบับ', modifiedText: 'ข้อความที่แก้ไข', regexPattern: 'รูปแบบ Regex', regexInput: 'อินพุต Regex', topText: 'ข้อความด้านบน', bottomText: 'ข้อความด้านล่าง', watermarkText: 'ข้อความลายน้ำ', foregroundColor: 'สีพื้นหน้า', backgroundColor: 'สีพื้นหลัง', generateQr: 'สร้าง QR', chooseQrImage: 'เลือกภาพ QR', exportClip: 'ส่งออกคลิป', compressImage: 'บีบอัดรูปภาพ', compressAllZip: 'บีบอัดทั้งหมดเป็น ZIP' },
  sv: { processing: 'Lokal bearbetning', inputs: 'Indata', browserSuffix: 'bearbetas i din webbläsare när verktyget stöder det.', externalSuffix: 'använder en konfigurerad extern bearbetningsslutpunkt och presenteras inte som enbart lokal.', chooseFile: 'Välj en fil', optional: 'Valfritt', originalText: 'Originaltext', modifiedText: 'Ändrad text', regexPattern: 'Regex-mönster', regexInput: 'Regex-indata', topText: 'Övre text', bottomText: 'Nedre text', watermarkText: 'Vattenstämpeltext', foregroundColor: 'Förgrundsfärg', backgroundColor: 'Bakgrundsfärg', generateQr: 'Skapa QR', chooseQrImage: 'Välj QR-bild', exportClip: 'Exportera klipp', compressImage: 'Komprimera bild', compressAllZip: 'Komprimera allt till ZIP' },
  ms: { processing: 'Pemprosesan tempatan', inputs: 'Input', browserSuffix: 'diproses dalam pelayar anda apabila alat menyokongnya.', externalSuffix: 'menggunakan titik akhir pemprosesan luaran yang dikonfigurasi dan tidak dipersembahkan sebagai tempatan sahaja.', chooseFile: 'Pilih fail', optional: 'Pilihan', originalText: 'Teks asal', modifiedText: 'Teks diubah suai', regexPattern: 'Corak Regex', regexInput: 'Input Regex', topText: 'Teks atas', bottomText: 'Teks bawah', watermarkText: 'Teks tera air', foregroundColor: 'Warna latar hadapan', backgroundColor: 'Warna latar belakang', generateQr: 'Jana QR', chooseQrImage: 'Pilih imej QR', exportClip: 'Eksport klip', compressImage: 'Mampatkan imej', compressAllZip: 'Mampatkan semua ke ZIP' },
  uk: { processing: 'Локальна обробка', inputs: 'Вхідні дані', browserSuffix: 'обробляються у вашому браузері, коли інструмент це підтримує.', externalSuffix: 'використовує налаштовану зовнішню точку обробки й не подається як лише локальний.', chooseFile: 'Виберіть файл', optional: 'Необов’язково', originalText: 'Оригінальний текст', modifiedText: 'Змінений текст', regexPattern: 'Шаблон Regex', regexInput: 'Ввід Regex', topText: 'Верхній текст', bottomText: 'Нижній текст', watermarkText: 'Текст водяного знака', foregroundColor: 'Колір переднього плану', backgroundColor: 'Колір фону', generateQr: 'Створити QR', chooseQrImage: 'Виберіть зображення QR', exportClip: 'Експортувати кліп', compressImage: 'Стиснути зображення', compressAllZip: 'Стиснути все в ZIP' },
};

export function translateSharedToolText(locale: Locale, value: string): string {
  if (locale === 'en') return value;
  const copy = SHARED_TOOL_UI_COPY[locale] ?? SHARED_TOOL_UI_COPY.en;
  const compact = value.trim();

  const localMatch = compact.match(/^●\s*Local processing Inputs for (.+?) are processed in your browser when supported by the tool\.$/);
  if (localMatch) {
    const title = localMatch[1].trim();
    return `● ${copy.processing}: ${copy.inputs} — ${title} ${copy.browserSuffix}`;
  }

  const externalMatch = compact.match(/^↗\s*External processing (.+?) uses a configured external processing endpoint and is not presented as local-only\.$/);
  if (externalMatch) {
    const title = externalMatch[1].trim();
    return `↗ ${copy.processing === 'معالجة محلية' ? 'معالجة خارجية' : copy.processing.replace(/محلية|local|Lokal|locale|Локальная|ローカル|स्थानीय|Yerel|Lokal|Pemprosesan tempatan|Локальна|本地|Xử lý cục bộ|การประมวลผลภายในเครื่อง/, locale === 'ar' ? 'معالجة خارجية' : String(locale) === 'zh' ? '外部处理' : locale === 'uk' ? 'Зовнішня обробка' : 'External processing')} ${title} ${copy.externalSuffix}`;
  }

  const exact = new Map<string, string>([
    ['Choose a file', copy.chooseFile], ['Optional', copy.optional], ['Original text', copy.originalText], ['Modified text', copy.modifiedText], ['Regex pattern', copy.regexPattern], ['Regex input', copy.regexInput], ['Top text', copy.topText], ['Bottom text', copy.bottomText], ['Watermark text', copy.watermarkText], ['Foreground color', copy.foregroundColor], ['Background color', copy.backgroundColor], ['Generate QR', copy.generateQr], ['Choose QR image', copy.chooseQrImage], ['Export clip', copy.exportClip], ['Compress image', copy.compressImage], ['Compress all to ZIP', copy.compressAllZip],
  ]);
  const replacement = exact.get(compact);
  return replacement ? value.replace(compact, replacement) : value;
}
