import type { Locale } from './config';

type LocaleMap = Readonly<Partial<Record<string, string>>>;

const UI_SUPPLEMENT: Record<string, LocaleMap> = {
  'A cinematic sunset over Cairo...': {
    ar: 'غروب سينمائي فوق القاهرة...', de: 'Ein filmischer Sonnenuntergang über Kairo …', es: 'Una puesta de sol cinematográfica sobre El Cairo...', fr: 'Un coucher de soleil cinématographique sur Le Caire...', ru: 'Кинематографичный закат над Каиром…', zh: '开罗上空的电影感日落……', hi: 'काहिरा के ऊपर सिनेमाई सूर्यास्त...', id: 'Matahari terbenam sinematik di atas Kairo...', ur: 'قاہرہ کے اوپر ایک سنیماٹک غروبِ آفتاب...', ja: 'カイロの上に広がる映画のような夕日…', pt: 'Um pôr do sol cinematográfico sobre o Cairo...', it: 'Un tramonto cinematografico sul Cairo...', ko: '카이로 위의 영화 같은 일몰…', nl: 'Een filmische zonsondergang boven Caïro...', pl: 'Kinowy zachód słońca nad Kairem...', tr: 'Kahire üzerinde sinematik bir gün batımı...', vi: 'Hoàng hôn điện ảnh trên Cairo...', th: 'พระอาทิตย์ตกเหนือไคโรในแบบภาพยนตร์...', sv: 'En filmisk solnedgång över Kairo...'
  },
  'WebGPU WASM CPU': Object.fromEntries(['ar','de','es','fr','ru','zh','hi','id','ur','ja','pt','it','ko','nl','pl','tr','vi','th','sv'].map(locale => [locale, 'WebGPU · WASM · CPU'])) as LocaleMap,
  'Separate vocals / instrumental': {
    ar: 'فصل الغناء / الموسيقى', de: 'Gesang / Instrumental trennen', es: 'Separar voz / instrumental', fr: 'Séparer voix / instrumental', ru: 'Разделить вокал / инструментал', zh: '分离人声 / 伴奏', hi: 'वोकल / इंस्ट्रुमेंटल अलग करें', id: 'Pisahkan vokal / instrumental', ur: 'آواز / ساز الگ کریں', ja: 'ボーカル / インストゥルメンタルを分離', pt: 'Separar vocais / instrumental', it: 'Separa voce / strumentale', ko: '보컬 / 반주 분리', nl: 'Vocalen / instrumentaal scheiden', pl: 'Oddziel wokal / instrumental', tr: 'Vokal / enstrümantal ayır', vi: 'Tách giọng hát / nhạc nền', th: 'แยกเสียงร้อง / ดนตรี', sv: 'Separera sång / instrumental'
  },
  'Audio waveform': {
    ar: 'الموجة الصوتية', de: 'Audio-Wellenform', es: 'Forma de onda de audio', fr: 'Forme d’onde audio', ru: 'Аудиоволна', zh: '音频波形', hi: 'ऑडियो वेवफ़ॉर्म', id: 'Bentuk gelombang audio', ur: 'آڈیو موجی شکل', ja: 'オーディオ波形', pt: 'Forma de onda de áudio', it: 'Forma d’onda audio', ko: '오디오 파형', nl: 'Audiogolfvorm', pl: 'Fala audio', tr: 'Ses dalga biçimi', vi: 'Dạng sóng âm thanh', th: 'รูปคลื่นเสียง', sv: 'Ljudvågform'
  },
  Encode: { ar: 'ترميز', de: 'Kodieren', es: 'Codificar', fr: 'Encoder', ru: 'Кодировать', zh: '编码', hi: 'एन्कोड करें', id: 'Enkode', ur: 'انکوڈ کریں', ja: 'エンコード', pt: 'Codificar', it: 'Codifica', ko: '인코딩', nl: 'Coderen', pl: 'Koduj', tr: 'Kodla', vi: 'Mã hóa', th: 'เข้ารหัส', sv: 'Koda' },
  Decode: { ar: 'فك الترميز', de: 'Dekodieren', es: 'Decodificar', fr: 'Décoder', ru: 'Раздекодировать', zh: '解码', hi: 'डिकोड करें', id: 'Dekode', ur: 'ڈی کوڈ کریں', ja: 'デコード', pt: 'Decodificar', it: 'Decodifica', ko: '디코딩', nl: 'Decoderen', pl: 'Dekoduj', tr: 'Kodu çöz', vi: 'Giải mã', th: 'ถอดรหัส', sv: 'Avkoda' },
  'Preview Data URI': { ar: 'معاينة Data URI', de: 'Data-URI-Vorschau', es: 'Vista previa de Data URI', fr: 'Aperçu de Data URI', ru: 'Предпросмотр Data URI', zh: '预览 Data URI', hi: 'Data URI पूर्वावलोकन', id: 'Pratinjau Data URI', ur: 'Data URI پیش منظر', ja: 'Data URI をプレビュー', pt: 'Pré-visualizar Data URI', it: 'Anteprima Data URI', ko: 'Data URI 미리보기', nl: 'Data URI-voorbeeld', pl: 'Podgląd Data URI', tr: 'Data URI önizlemesi', vi: 'Xem trước Data URI', th: 'ดูตัวอย่าง Data URI', sv: 'Data URI-förhandsvisning' },
  Color: { ar: 'اللون', de: 'Farbe', es: 'Color', fr: 'Couleur', ru: 'Цвет', zh: '颜色', hi: 'रंग', id: 'Warna', ur: 'رنگ', ja: '色', pt: 'Cor', it: 'Colore', ko: '색상', nl: 'Kleur', pl: 'Kolor', tr: 'Renk', vi: 'Màu', th: 'สี', sv: 'Färg' },
  EyeDropper: { ar: 'قطّارة الألوان', de: 'Pipette', es: 'Cuentagotas', fr: 'Pipette', ru: 'Пипетка', zh: '取色器', hi: 'आईड्रॉपर', id: 'Pipet warna', ur: 'رنگ چننے والا', ja: 'スポイト', pt: 'Conta-gotas', it: 'Contagocce', ko: '스포이드', nl: 'Pipet', pl: 'Pipeta', tr: 'Damlalık', vi: 'Ống nhỏ giọt', th: 'หลอดดูดสี', sv: 'Pipett' },
  'color-preview': { ar: 'معاينة اللون', de: 'Farbvorschau', es: 'Vista previa del color', fr: 'Aperçu des couleurs', ru: 'Предпросмотр цвета', zh: '颜色预览', hi: 'रंग पूर्वावलोकन', id: 'Pratinjau warna', ur: 'رنگ پیش منظر', ja: 'カラープレビュー', pt: 'Pré-visualização da cor', it: 'Anteprima colore', ko: '색상 미리보기', nl: 'Kleurvoorbeeld', pl: 'Podgląd koloru', tr: 'Renk önizlemesi', vi: 'Xem trước màu', th: 'ตัวอย่างสี', sv: 'Färgförhandsvisning' },
  Background: { ar: 'الخلفية', de: 'Hintergrund', es: 'Fondo', fr: 'Arrière-plan', ru: 'Фон', zh: '背景', hi: 'पृष्ठभूमि', id: 'Latar belakang', ur: 'پس منظر', ja: '背景', pt: 'Plano de fundo', it: 'Sfondo', ko: '배경', nl: 'Achtergrond', pl: 'Tło', tr: 'Arka plan', vi: 'Nền', th: 'พื้นหลัง', sv: 'Bakgrund' },
  'Copy HEX': { ar: 'نسخ HEX', de: 'HEX kopieren', es: 'Copiar HEX', fr: 'Copier HEX', ru: 'Копировать HEX', zh: '复制 HEX', hi: 'HEX कॉपी करें', id: 'Salin HEX', ur: 'HEX کاپی کریں', ja: 'HEXをコピー', pt: 'Copiar HEX', it: 'Copia HEX', ko: 'HEX 복사', nl: 'HEX kopiëren', pl: 'Kopiuj HEX', tr: 'HEX’i kopyala', vi: 'Sao chép HEX', th: 'คัดลอก HEX', sv: 'Kopiera HEX' },
  'Copy RGB': { ar: 'نسخ RGB', de: 'RGB kopieren', es: 'Copiar RGB', fr: 'Copier RGB', ru: 'Копировать RGB', zh: '复制 RGB', hi: 'RGB कॉपी करें', id: 'Salin RGB', ur: 'RGB کاپی کریں', ja: 'RGBをコピー', pt: 'Copiar RGB', it: 'Copia RGB', ko: 'RGB 복사', nl: 'RGB kopiëren', pl: 'Kopiuj RGB', tr: 'RGB’yi kopyala', vi: 'Sao chép RGB', th: 'คัดลอก RGB', sv: 'Kopiera RGB' },
  'Copy Tailwind': { ar: 'نسخ Tailwind', de: 'Tailwind kopieren', es: 'Copiar Tailwind', fr: 'Copier Tailwind', ru: 'Копировать Tailwind', zh: '复制 Tailwind', hi: 'Tailwind कॉपी करें', id: 'Salin Tailwind', ur: 'Tailwind کاپی کریں', ja: 'Tailwindをコピー', pt: 'Copiar Tailwind', it: 'Copia Tailwind', ko: 'Tailwind 복사', nl: 'Tailwind kopiëren', pl: 'Kopiuj Tailwind', tr: 'Tailwind’i kopyala', vi: 'Sao chép Tailwind', th: 'คัดลอก Tailwind', sv: 'Kopiera Tailwind' },
  'Converted output': { ar: 'الناتج المحوّل', de: 'Konvertierte Ausgabe', es: 'Salida convertida', fr: 'Sortie convertie', ru: 'Преобразованный результат', zh: '转换后的输出', hi: 'रूपांतरित आउटपुट', id: 'Hasil konversi', ur: 'تبدیل شدہ نتیجہ', ja: '変換後の出力', pt: 'Saída convertida', it: 'Output convertito', ko: '변환된 출력', nl: 'Geconverteerde uitvoer', pl: 'Przekonwertowane wyjście', tr: 'Dönüştürülen çıktı', vi: 'Đầu ra đã chuyển đổi', th: 'ผลลัพธ์ที่แปลงแล้ว', sv: 'Konverterad utdata' },
  'Characters 0 Words 0 Mode UPPERCASE': { ar: 'الأحرف 0 الكلمات 0 الوضع أحرف كبيرة', de: 'Zeichen 0 Wörter 0 Modus GROSSBUCHSTABEN', es: 'Caracteres 0 Palabras 0 Modo MAYÚSCULAS', fr: 'Caractères 0 Mots 0 Mode MAJUSCULES', ru: 'Символы 0 Слова 0 Режим ПРОПИСНЫЕ', zh: '字符 0 单词 0 模式 大写', hi: 'अक्षर 0 शब्द 0 मोड बड़े अक्षर', id: 'Karakter 0 Kata 0 Mode HURUF BESAR', ur: 'حروف 0 الفاظ 0 موڈ بڑے حروف', ja: '文字 0 単語 0 モード 大文字', pt: 'Caracteres 0 Palavras 0 Modo MAIÚSCULAS', it: 'Caratteri 0 Parole 0 Modalità MAIUSCOLO', ko: '문자 0 단어 0 모드 대문자', nl: 'Tekens 0 Woorden 0 Modus HOOFDLETTERS', pl: 'Znaki 0 Słowa 0 Tryb WIELKIE LITERY', tr: 'Karakter 0 Kelime 0 Mod BÜYÜK HARF', vi: 'Ký tự 0 Từ 0 Chế độ CHỮ HOA', th: 'อักขระ 0 คำ 0 โหมด ตัวพิมพ์ใหญ่', sv: 'Tecken 0 Ord 0 Läge VERSALER' },
  'Text to hash': { ar: 'نص لإنشاء التجزئة', de: 'Text zum Hashen', es: 'Texto para generar hash', fr: 'Texte à hacher', ru: 'Текст для хеширования', zh: '要哈希的文本', hi: 'हैश के लिए टेक्स्ट', id: 'Teks untuk hash', ur: 'ہیش کے لیے متن', ja: 'ハッシュ化するテキスト', pt: 'Texto para gerar hash', it: 'Testo da sottoporre a hash', ko: '해시할 텍스트', nl: 'Tekst om te hashen', pl: 'Tekst do haszowania', tr: 'Hashlenecek metin', vi: 'Văn bản để băm', th: 'ข้อความสำหรับแฮช', sv: 'Text att hasha' },
  'Hash result': { ar: 'نتيجة التجزئة', de: 'Hash-Ergebnis', es: 'Resultado del hash', fr: 'Résultat du hachage', ru: 'Результат хеширования', zh: '哈希结果', hi: 'हैश परिणाम', id: 'Hasil hash', ur: 'ہیش نتیجہ', ja: 'ハッシュ結果', pt: 'Resultado do hash', it: 'Risultato hash', ko: '해시 결과', nl: 'Hashresultaat', pl: 'Wynik haszowania', tr: 'Hash sonucu', vi: 'Kết quả băm', th: 'ผลลัพธ์แฮช', sv: 'Hashresultat' },
  Auto: { ar: 'تلقائي', de: 'Automatisch', es: 'Automático', fr: 'Automatique', ru: 'Авто', zh: '自动', hi: 'स्वचालित', id: 'Otomatis', ur: 'خودکار', ja: '自動', pt: 'Automático', it: 'Automatico', ko: '자동', nl: 'Automatisch', pl: 'Automatycznie', tr: 'Otomatik', vi: 'Tự động', th: 'อัตโนมัติ', sv: 'Automatiskt' },
  'Create PDF': { ar: 'إنشاء PDF', de: 'PDF erstellen', es: 'Crear PDF', fr: 'Créer un PDF', ru: 'Создать PDF', zh: '创建 PDF', hi: 'PDF बनाएँ', id: 'Buat PDF', ur: 'PDF بنائیں', ja: 'PDFを作成', pt: 'Criar PDF', it: 'Crea PDF', ko: 'PDF 만들기', nl: 'PDF maken', pl: 'Utwórz PDF', tr: 'PDF oluştur', vi: 'Tạo PDF', th: 'สร้าง PDF', sv: 'Skapa PDF' },
  Prettify: { ar: 'تنسيق', de: 'Formatieren', es: 'Embellecer', fr: 'Mettre en forme', ru: 'Форматировать', zh: '美化', hi: 'सजाएँ', id: 'Percantik', ur: 'خوبصورت بنائیں', ja: '整形', pt: 'Formatar', it: 'Formatta', ko: '정렬', nl: 'Formatteren', pl: 'Formatuj', tr: 'Biçimlendir', vi: 'Định dạng', th: 'จัดรูปแบบ', sv: 'Formatera' },
  Minify: { ar: 'تصغير', de: 'Minimieren', es: 'Minificar', fr: 'Minifier', ru: 'Минифицировать', zh: '压缩', hi: 'मिनिफ़ाई करें', id: 'Minifikasi', ur: 'مختصر کریں', ja: '最小化', pt: 'Minificar', it: 'Minifica', ko: '최소화', nl: 'Minificeren', pl: 'Minifikuj', tr: 'Küçült', vi: 'Thu nhỏ', th: 'ย่อขนาด', sv: 'Förminska' },
  'Tree View': { ar: 'عرض شجري', de: 'Baumansicht', es: 'Vista de árbol', fr: 'Vue arborescente', ru: 'Дерево', zh: '树视图', hi: 'ट्री व्यू', id: 'Tampilan pohon', ur: 'درختی منظر', ja: 'ツリービュー', pt: 'Visão em árvore', it: 'Vista ad albero', ko: '트리 보기', nl: 'Boomweergave', pl: 'Widok drzewa', tr: 'Ağaç görünümü', vi: 'Chế độ cây', th: 'มุมมองแบบต้นไม้', sv: 'Trädvy' },
  'JSON input': { ar: 'إدخال JSON', de: 'JSON-Eingabe', es: 'Entrada JSON', fr: 'Entrée JSON', ru: 'Ввод JSON', zh: 'JSON 输入', hi: 'JSON इनपुट', id: 'Input JSON', ur: 'JSON ان پٹ', ja: 'JSON入力', pt: 'Entrada JSON', it: 'Input JSON', ko: 'JSON 입력', nl: 'JSON-invoer', pl: 'Wejście JSON', tr: 'JSON girişi', vi: 'Đầu vào JSON', th: 'อินพุต JSON', sv: 'JSON-inmatning' },
  'JSON output': { ar: 'إخراج JSON', de: 'JSON-Ausgabe', es: 'Salida JSON', fr: 'Sortie JSON', ru: 'Вывод JSON', zh: 'JSON 输出', hi: 'JSON आउटपुट', id: 'Output JSON', ur: 'JSON آؤٹ پٹ', ja: 'JSON出力', pt: 'Saída JSON', it: 'Output JSON', ko: 'JSON 출력', nl: 'JSON-uitvoer', pl: 'Wyjście JSON', tr: 'JSON çıktısı', vi: 'Đầu ra JSON', th: 'เอาต์พุต JSON', sv: 'JSON-utdata' },
  'Merge 0 pages': { ar: 'دمج 0 صفحة', de: '0 Seiten zusammenführen', es: 'Combinar 0 páginas', fr: 'Fusionner 0 pages', ru: 'Объединить 0 страниц', zh: '合并 0 页', hi: '0 पृष्ठ मर्ज करें', id: 'Gabungkan 0 halaman', ur: '0 صفحات ضم کریں', ja: '0ページを結合', pt: 'Mesclar 0 páginas', it: 'Unisci 0 pagine', ko: '0페이지 병합', nl: '0 pagina’s samenvoegen', pl: 'Połącz 0 stron', tr: '0 sayfayı birleştir', vi: 'Gộp 0 trang', th: 'รวม 0 หน้า', sv: 'Slå ihop 0 sidor' },
  'Rotate selected': { ar: 'تدوير المحدد', de: 'Auswahl drehen', es: 'Girar seleccionados', fr: 'Faire pivoter la sélection', ru: 'Повернуть выбранное', zh: '旋转所选', hi: 'चयनित घुमाएँ', id: 'Putar yang dipilih', ur: 'منتخب کو گھمائیں', ja: '選択項目を回転', pt: 'Girar selecionado', it: 'Ruota selezionato', ko: '선택 항목 회전', nl: 'Selectie roteren', pl: 'Obróć zaznaczone', tr: 'Seçileni döndür', vi: 'Xoay mục đã chọn', th: 'หมุนรายการที่เลือก', sv: 'Rotera valda' },
  'Move ↑': { ar: 'تحريك ↑', de: 'Nach oben ↑', es: 'Mover ↑', fr: 'Déplacer ↑', ru: 'Переместить ↑', zh: '上移 ↑', hi: 'ऊपर ले जाएँ ↑', id: 'Pindah ↑', ur: 'اوپر منتقل کریں ↑', ja: '上へ移動 ↑', pt: 'Mover ↑', it: 'Sposta ↑', ko: '위로 이동 ↑', nl: 'Omhoog verplaatsen ↑', pl: 'Przenieś ↑', tr: 'Yukarı taşı ↑', vi: 'Di chuyển ↑', th: 'ย้ายขึ้น ↑', sv: 'Flytta upp ↑' },
  'Move ↓': { ar: 'تحريك ↓', de: 'Nach unten ↓', es: 'Mover ↓', fr: 'Déplacer ↓', ru: 'Переместить ↓', zh: '下移 ↓', hi: 'नीचे ले जाएँ ↓', id: 'Pindah ↓', ur: 'نیچے منتقل کریں ↓', ja: '下へ移動 ↓', pt: 'Mover ↓', it: 'Sposta ↓', ko: '아래로 이동 ↓', nl: 'Omlaag verplaatsen ↓', pl: 'Przenieś ↓', tr: 'Aşağı taşı ↓', vi: 'Di chuyển ↓', th: 'ย้ายลง ↓', sv: 'Flytta ner ↓' },
  Delete: { ar: 'حذف', de: 'Löschen', es: 'Eliminar', fr: 'Supprimer', ru: 'Удалить', zh: '删除', hi: 'हटाएँ', id: 'Hapus', ur: 'حذف کریں', ja: '削除', pt: 'Excluir', it: 'Elimina', ko: '삭제', nl: 'Verwijderen', pl: 'Usuń', tr: 'Sil', vi: 'Xóa', th: 'ลบ', sv: 'Ta bort' },
  'Page range': { ar: 'نطاق الصفحات', de: 'Seitenbereich', es: 'Rango de páginas', fr: 'Plage de pages', ru: 'Диапазон страниц', zh: '页码范围', hi: 'पृष्ठ सीमा', id: 'Rentang halaman', ur: 'صفحے کی حد', ja: 'ページ範囲', pt: 'Intervalo de páginas', it: 'Intervallo di pagine', ko: '페이지 범위', nl: 'Paginabereik', pl: 'Zakres stron', tr: 'Sayfa aralığı', vi: 'Phạm vi trang', th: 'ช่วงหน้า', sv: 'Sidintervall' },
  'Split range': { ar: 'نطاق التقسيم', de: 'Teilbereich', es: 'Rango de división', fr: 'Plage de séparation', ru: 'Диапазон разделения', zh: '拆分范围', hi: 'विभाजन सीमा', id: 'Rentang pemisahan', ur: 'تقسیمی حد', ja: '分割範囲', pt: 'Intervalo de divisão', it: 'Intervallo di divisione', ko: '분할 범위', nl: 'Splitsbereik', pl: 'Zakres dzielenia', tr: 'Bölme aralığı', vi: 'Phạm vi tách', th: 'ช่วงแบ่ง', sv: 'Delningsintervall' },
  'Protect PDFUnlock PDF': { ar: 'حماية PDFفتح قفل PDF', de: 'PDF schützenPDF entsperren', es: 'Proteger PDFDesbloquear PDF', fr: 'Protéger PDFDéverrouiller PDF', ru: 'Защитить PDFРазблокировать PDF', zh: '保护 PDF解锁 PDF', hi: 'PDF सुरक्षित करेंPDF अनलॉक करें', id: 'Lindungi PDFBuka kunci PDF', ur: 'PDF محفوظ کریںPDF ان لاک کریں', ja: 'PDFを保護PDFのロックを解除', pt: 'Proteger PDFDesbloquear PDF', it: 'Proteggi PDFSblocca PDF', ko: 'PDF 보호PDF 잠금 해제', nl: 'PDF beveiligenPDF ontgrendelen', pl: 'Chroń PDFOdblokuj PDF', tr: 'PDF’yi koruPDF’nin kilidini aç', vi: 'Bảo vệ PDFMở khóa PDF', th: 'ป้องกัน PDFปลดล็อก PDF', sv: 'Skydda PDFLås upp PDF' },
  'Protect PDF': { ar: 'حماية PDF', de: 'PDF schützen', es: 'Proteger PDF', fr: 'Protéger PDF', ru: 'Защитить PDF', zh: '保护 PDF', hi: 'PDF सुरक्षित करें', id: 'Lindungi PDF', ur: 'PDF محفوظ کریں', ja: 'PDFを保護', pt: 'Proteger PDF', it: 'Proteggi PDF', ko: 'PDF 보호', nl: 'PDF beveiligen', pl: 'Chroń PDF', tr: 'PDF’yi koru', vi: 'Bảo vệ PDF', th: 'ป้องกัน PDF', sv: 'Skydda PDF' },
  'Unlock PDF': { ar: 'فتح قفل PDF', de: 'PDF entsperren', es: 'Desbloquear PDF', fr: 'Déverrouiller PDF', ru: 'Разблокировать PDF', zh: '解锁 PDF', hi: 'PDF अनलॉक करें', id: 'Buka kunci PDF', ur: 'PDF ان لاک کریں', ja: 'PDFのロックを解除', pt: 'Desbloquear PDF', it: 'Sblocca PDF', ko: 'PDF 잠금 해제', nl: 'PDF ontgrendelen', pl: 'Odblokuj PDF', tr: 'PDF’nin kilidini aç', vi: 'Mở khóa PDF', th: 'ปลดล็อก PDF', sv: 'Lås upp PDF' },
  'Enter password': { ar: 'أدخل كلمة المرور', de: 'Passwort eingeben', es: 'Introducir contraseña', fr: 'Saisir le mot de passe', ru: 'Введите пароль', zh: '输入密码', hi: 'पासवर्ड दर्ज करें', id: 'Masukkan kata sandi', ur: 'پاس ورڈ درج کریں', ja: 'パスワードを入力', pt: 'Digite a senha', it: 'Inserisci la password', ko: '비밀번호 입력', nl: 'Voer wachtwoord in', pl: 'Wprowadź hasło', tr: 'Parolayı girin', vi: 'Nhập mật khẩu', th: 'ป้อนรหัสผ่าน', sv: 'Ange lösenord' },
  'Defaults to user password': { ar: 'الافتراضي كلمة مرور المستخدم', de: 'Standardmäßig Benutzerpasswort', es: 'Predeterminado a la contraseña del usuario', fr: 'Par défaut, mot de passe utilisateur', ru: 'По умолчанию пароль пользователя', zh: '默认使用用户密码', hi: 'डिफ़ॉल्ट रूप से उपयोगकर्ता पासवर्ड', id: 'Default ke kata sandi pengguna', ur: 'پہلے سے صارف پاس ورڈ', ja: 'デフォルトはユーザーパスワード', pt: 'Padrão para a senha do usuário', it: 'Predefinito alla password utente', ko: '기본값은 사용자 비밀번호', nl: 'Standaard gebruikerswachtwoord', pl: 'Domyślnie hasło użytkownika', tr: 'Varsayılan kullanıcı parolası', vi: 'Mặc định là mật khẩu người dùng', th: 'ค่าเริ่มต้นเป็นรหัสผ่านผู้ใช้', sv: 'Standard är användarlösenord' }
};

export function translateSupplement(locale: Locale, value: string): string {
  if (locale === 'en') return value;
  const replacement = UI_SUPPLEMENT[value.trim()]?.[locale];
  return replacement ? value.replace(value.trim(), replacement) : value;
}

export function installToolUiRuntimeSupplement(): () => void {
  const translate = () => {
    const locale = document.documentElement.lang.split('-')[0] as Locale;
    if (!locale || locale === 'en' || !document.body) return;
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    while (walker.nextNode()) {
      const node = walker.currentNode as Text;
      const parent = node.parentElement;
      if (!node.nodeValue?.trim() || !parent || parent.closest('script,style,pre,textarea,[contenteditable="true"],[data-no-auto-i18n]')) continue;
      const next = translateSupplement(locale, node.nodeValue);
      if (next !== node.nodeValue) node.nodeValue = next;
    }
    document.body.querySelectorAll<HTMLElement>('[aria-label],[title],[placeholder]').forEach((element) => {
      if (element.matches('[data-no-auto-i18n]')) return;
      for (const attribute of ['aria-label', 'title', 'placeholder'] as const) {
        const value = element.getAttribute(attribute);
        if (!value) continue;
        const next = translateSupplement(locale, value);
        if (next !== value) element.setAttribute(attribute, next);
      }
    });
  };
  const observer = new MutationObserver(translate);
  translate();
  observer.observe(document.body, { subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: ['aria-label', 'title', 'placeholder'] });
  return () => observer.disconnect();
}
