import type { Locale } from './config';

export type ToolSeoLocale = Readonly<Record<Locale, string>>;

/** Canonical localized SEO names for image-platform tools only. */
const NEW_CANONICAL_IMAGE_SEO_LABELS: Readonly<Record<string, ToolSeoLocale>> = Object.freeze({
  'image-rotate-flip': { en:'Rotate & Flip', ar:'تدوير وقلب الصور', es:'Girar y voltear', fr:'Pivoter et retourner', de:'Drehen & Spiegeln', hi:'छवि घुमाएँ और पलटें', id:'Putar & Balik', it:'Ruota e capovolgi', ja:'回転と反転', ko:'회전 및 뒤집기', ms:'Putar & Balik', nl:'Draaien & Spiegelen', pl:'Obracanie i odbicie', pt:'Girar e espelhar', ru:'Поворот и отражение', sv:'Rotera och spegla', th:'หมุนและพลิกรูปภาพ', tr:'Döndür ve Çevir', uk:'Поворот і віддзеркалення', vi:'Xoay & Lật' },
  'image-brightness-contrast': { en:'Brightness & Contrast', ar:'السطوع والتباين', es:'Brillo y contraste', fr:'Luminosité et contraste', de:'Helligkeit & Kontrast', hi:'चमक और कंट्रास्ट', id:'Kecerahan & Kontras', it:'Luminosità e contrasto', ja:'明るさとコントラスト', ko:'밝기 및 대비', ms:'Kecerahan & Kontras', nl:'Helderheid & Contrast', pl:'Jasność i kontrast', pt:'Brilho e contraste', ru:'Яркость и контраст', sv:'Ljusstyrka och kontrast', th:'ความสว่างและคอนทราสต์', tr:'Parlaklık ve Kontrast', uk:'Яскравість і контраст', vi:'Độ sáng & Độ tương phản' },
  'image-saturation-hue': { en:'Saturation & Hue', ar:'التشبع ودرجة اللون', es:'Saturación y tono', fr:'Saturation et teinte', de:'Sättigung & Farbton', hi:'संतृप्ति और ह्यू', id:'Saturasi & Hue', it:'Saturazione e tonalità', ja:'彩度と色相', ko:'채도 및 색조', ms:'Ketepuan & Rona', nl:'Verzadiging & Tint', pl:'Nasycenie i odcień', pt:'Saturação e matiz', ru:'Насыщенность и оттенок', sv:'Mättnad och nyans', th:'ความอิ่มตัวและเฉดสี', tr:'Doygunluk ve Ton', uk:'Насиченість і відтінок', vi:'Độ bão hòa & Sắc độ' },
  'image-exposure': { en:'Exposure', ar:'التعريض', es:'Exposición', fr:'Exposition', de:'Belichtung', hi:'एक्सपोज़र', id:'Eksposur', it:'Esposizione', ja:'露出', ko:'노출', ms:'Pendedahan', nl:'Belichting', pl:'Ekspozycja', pt:'Exposição', ru:'Экспозиция', sv:'Exponering', th:'ค่าแสง', tr:'Pozlama', uk:'Експозиція', vi:'Phơi sáng' },
  'image-highlights-shadows': { en:'Highlights & Shadows', ar:'الإبرازات والظلال', es:'Luces y sombras', fr:'Hautes lumières et ombres', de:'Lichter & Schatten', hi:'हाइलाइट और शैडो', id:'Sorotan & Bayangan', it:'Luci e ombre', ja:'ハイライトとシャドウ', ko:'하이라이트 및 그림자', ms:'Sorotan & Bayang', nl:'Lichtpartijen & Schaduwen', pl:'Światła i cienie', pt:'Altas luzes e sombras', ru:'Света и тени', sv:'Högdagrar och skuggor', th:'ไฮไลต์และเงา', tr:'Parlak alanlar ve Gölgeler', uk:'Світлі ділянки й тіні', vi:'Vùng sáng & Bóng' },
  'image-grayscale-duotone': { en:'Grayscale & Duotone', ar:'التدرج الرمادي ودوتون', es:'Escala de grises y duotono', fr:'Niveaux de gris et duotone', de:'Graustufen & Duotone', hi:'ग्रेस्केल और डुओटोन', id:'Skala Abu-abu & Duotone', it:'Scala di grigi e duotone', ja:'グレースケールとデュオトーン', ko:'그레이스케일 및 듀오톤', ms:'Skala Kelabu & Duoton', nl:'Grijstinten & Duotoon', pl:'Skala szarości i duoton', pt:'Escala de cinza e duotônico', ru:'Градации серого и дуотон', sv:'Gråskala och duoton', th:'โทนสีเทาและดูโอโทน', tr:'Gri Tonlama ve Duotone', uk:'Градації сірого та дуотон', vi:'Thang xám & Duotone' },
  'image-filters': { en:'Image Filters', ar:'فلاتر الصور', es:'Filtros de imagen', fr:'Filtres d’image', de:'Bildfilter', hi:'इमेज फ़िल्टर', id:'Filter Gambar', it:'Filtri immagine', ja:'画像フィルター', ko:'이미지 필터', ms:'Penapis Imej', nl:'Afbeeldingsfilters', pl:'Filtry obrazu', pt:'Filtros de imagem', ru:'Фильтры изображения', sv:'Bildfilter', th:'ฟิลเตอร์รูปภาพ', tr:'Görsel Filtreleri', uk:'Фільтри зображень', vi:'Bộ lọc ảnh' },
  'image-watermark': { en:'Watermark', ar:'العلامة المائية', es:'Marca de agua', fr:'Filigrane', de:'Wasserzeichen', hi:'वॉटरमार्क', id:'Tanda Air', it:'Filigrana', ja:'透かし', ko:'워터마크', ms:'Tanda Air', nl:'Watermerk', pl:'Znak wodny', pt:'Marca d’água', ru:'Водяной знак', sv:'Vattenstämpel', th:'ลายน้ำ', tr:'Filigran', uk:'Водяний знак', vi:'Hình mờ' },
  'image-text-overlay': { en:'Text Overlay', ar:'إضافة نص على الصورة', es:'Superposición de texto', fr:'Superposition de texte', de:'Textüberlagerung', hi:'टेक्स्ट ओवरले', id:'Hamparan Teks', it:'Sovrapposizione testo', ja:'テキストオーバーレイ', ko:'텍스트 오버레이', ms:'Tindanan Teks', nl:'Tekstoverlay', pl:'Nakładka tekstowa', pt:'Sobreposição de texto', ru:'Наложение текста', sv:'Textöverlägg', th:'ซ้อนข้อความ', tr:'Metin Kaplaması', uk:'Накладання тексту', vi:'Lớp phủ văn bản' },
  'image-draw-annotate': { en:'Draw & Annotate', ar:'الرسم والتعليق على الصورة', es:'Dibujar y anotar', fr:'Dessiner et annoter', de:'Zeichnen & Anmerken', hi:'ड्रॉ और एनोटेट', id:'Gambar & Anotasi', it:'Disegno e annotazione', ja:'描画と注釈', ko:'그리기 및 주석', ms:'Lukis & Anotasi', nl:'Tekenen & Annoteren', pl:'Rysowanie i adnotacje', pt:'Desenho e anotações', ru:'Рисование и аннотации', sv:'Rita och kommentera', th:'วาดและใส่คำอธิบาย', tr:'Çiz ve Açıkla', uk:'Малювання й анотації', vi:'Vẽ & Chú thích' },
  'image-redaction': { en:'Image Redaction', ar:'تعمية الصورة', es:'Censura de imagen', fr:'Caviardage d’image', de:'Bild-Schwärzung', hi:'इमेज रिडैक्शन', id:'Redaksi Gambar', it:'Oscuramento immagine', ja:'画像の墨消し', ko:'이미지 가리기', ms:'Penyamaran Imej', nl:'Afbeelding redigeren', pl:'Redakcja obrazu', pt:'Redação de imagem', ru:'Редактирование изображения', sv:'Bildmaskering', th:'ปกปิดข้อมูลในภาพ', tr:'Görsel Sansürleme', uk:'Редагування зображення', vi:'Che nội dung ảnh' },
});

const NEW_CANONICAL_IMAGE_SEO_NAMES: Readonly<Record<string, ToolSeoLocale>> = Object.freeze(
  Object.fromEntries(Object.entries(NEW_CANONICAL_IMAGE_SEO_LABELS)) as Readonly<Record<string, ToolSeoLocale>>,
);

export const TOOL_SEO_NAMES: Readonly<Record<string, ToolSeoLocale>> = Object.freeze({
  'filter-mask': Object.freeze({ en:'Filter Mask', ar:'قناع الفلاتر', es:'Máscara de filtros', fr:'Masque de filtres', de:'Filtermaske', hi:'फ़िल्टर मास्क', id:'Masker filter', it:'Maschera filtro', ja:'フィルターマスク', ko:'필터 마스크', ms:'Topeng penapis', nl:'Filtermasker', pl:'Maska filtrów', pt:'Máscara de filtros', ru:'Маска фильтров', sv:'Filtermask', th:'มาสก์ฟิลเตอร์', tr:'Filtre maskesi', uk:'Маска фільтрів', vi:'Mặt nạ bộ lọc' }),
  'image-compressor': Object.freeze({ en:'Image Compressor', ar:'ضاغط الصور', es:'Compresor de imágenes', fr:"Compresseur d’images", de:'Bildkompressor', hi:'इमेज कंप्रेसर', id:'Kompresor Gambar', it:'Compressore di immagini', ja:'画像圧縮', ko:'이미지 압축기', ms:'Pemampat Imej', nl:'Afbeeldingscompressor', pl:'Kompresor obrazów', pt:'Compressor de Imagens', ru:'Компрессор изображений', sv:'Bildkompressor', th:'เครื่องมือบีบอัดรูปภาพ', tr:'Görsel sıkıştırıcı', uk:'Компресор зображень', vi:'Trình nén ảnh' }),
  'background-remover': Object.freeze({ en:'Background Remover', ar:'إزالة خلفية الصور', es:'Eliminador de fondos', fr:'Suppression d’arrière-plan', de:'Hintergrund entfernen', hi:'बैकग्राउंड रिमूवर', id:'Penghapus Latar Belakang', it:'Rimozione sfondo', ja:'背景削除', ko:'배경 제거', ms:'Penyingkir Latar Belakang', nl:'Achtergrond verwijderen', pl:'Usuwanie tła', pt:'Removedor de Fundo', ru:'Удаление фона', sv:'Ta bort bakgrund', th:'ลบพื้นหลัง', tr:'Arka plan kaldırma', uk:'Видалення фону', vi:'Xóa nền ảnh' }),
  'image-upscaler': Object.freeze({ en:'Image Upscaler', ar:'تكبير الصور وتحسين دقتها', es:'Mejorador de resolución de imágenes', fr:'Améliorateur de résolution d’images', de:'Bild-Hochskalierer', hi:'इमेज अपस्केलर', id:'Peningkat Resolusi Gambar', it:'Upscaler di immagini', ja:'画像高画質化', ko:'이미지 업스케일러', ms:'Peningkat Resolusi Imej', nl:'Afbeeldingen opschalen', pl:'Skalowanie obrazów', pt:'Upscaler de Imagens', ru:'Масштабирование изображений', sv:'Bilduppskalare', th:'เพิ่มความละเอียดรูปภาพ', tr:'Görsel büyütücü', uk:'Збільшувач зображень', vi:'Tăng độ phân giải ảnh' }),
  'image-converter': Object.freeze({ en:'Image Converter', ar:'محول الصور', es:'Convertidor de imágenes', fr:'Convertisseur d’images', de:'Bildkonverter', hi:'इमेज कनवर्टर', id:'Konverter Gambar', it:'Convertitore di immagini', ja:'画像変換', ko:'이미지 변환기', ms:'Penukar Imej', nl:'Afbeeldingsconverter', pl:'Konwerter obrazów', pt:'Conversor de Imagens', ru:'Конвертер изображений', sv:'Bildkonverterare', th:'ตัวแปลงรูปภาพ', tr:'Görsel dönüştürücü', uk:'Конвертер зображень', vi:'Trình chuyển đổi ảnh' }),
  'object-remover': Object.freeze({ en:'Object Remover', ar:'إزالة العناصر من الصور', es:'Eliminador de objetos', fr:'Suppression d’objets', de:'Objekte entfernen', hi:'ऑब्जेक्ट रिमूवर', id:'Penghapus Objek', it:'Rimozione oggetti', ja:'オブジェクト削除', ko:'개체 제거', ms:'Penyingkir Objek', nl:'Objecten verwijderen', pl:'Usuwanie obiektów', pt:'Removedor de Objetos', ru:'Удаление объектов', sv:'Ta bort objekt', th:'ลบวัตถุ', tr:'Nesne kaldırma', uk:'Видалення об’єктів', vi:'Xóa đối tượng' }),
  'watermark-remover': Object.freeze({ en:'Watermark Remover', ar:'إزالة العلامة المائية', es:'Eliminador de marcas de agua', fr:'Suppression de filigrane', de:'Wasserzeichen entfernen', hi:'वॉटरमार्क रिमूवर', id:'Penghapus Tanda Air', it:'Rimozione filigrana', ja:'透かし削除', ko:'워터마크 제거', ms:'Penyingkir Tanda Air', nl:'Watermerk verwijderen', pl:'Usuwanie znaków wodnych', pt:'Removedor de Marca d’água', ru:'Удаление водяных знаков', sv:'Ta bort vattenstämpel', th:'ลบลายน้ำ', tr:'Filigran kaldırma', uk:'Видалення водяних знаків', vi:'Xóa hình mờ' }),
  'image-cropper': Object.freeze({ en:'Image Cropper', ar:'قص الصور وتغيير حجمها', es:'Recortador de imágenes', fr:'Recadrage d’images', de:'Bild zuschneiden', hi:'इमेज क्रॉपर', id:'Pemotong Gambar', it:'Ritaglio immagini', ja:'画像トリミング', ko:'이미지 자르기', ms:'Pemotong Imej', nl:'Afbeeldingen bijsnijden', pl:'Kadrowanie obrazów', pt:'Cortador de Imagens', ru:'Обрезка изображений', sv:'Beskär bilder', th:'ครอบตัดรูปภาพ', tr:'Görsel kırpma', uk:'Обрізувач зображень', vi:'Cắt ảnh' }),
  'image-to-svg': Object.freeze({ en:'Image to SVG Converter', ar:'تحويل الصور إلى SVG', es:'Convertidor de imagen a SVG', fr:'Convertisseur d’image en SVG', de:'Bild-zu-SVG-Konverter', hi:'इमेज से SVG कनवर्टर', id:'Konverter Gambar ke SVG', it:'Convertitore da immagine a SVG', ja:'画像からSVG変換', ko:'이미지 SVG 변환기', ms:'Penukar Imej kepada SVG', nl:'Afbeelding naar SVG converter', pl:'Konwerter obrazu do SVG', pt:'Conversor de Imagem para SVG', ru:'Конвертер изображения в SVG', sv:'Bild till SVG-konverterare', th:'แปลงรูปภาพเป็น SVG', tr:'Görselden SVG dönüştürücü', uk:'Конвертер зображень у SVG', vi:'Trình chuyển ảnh sang SVG' }),
  'image-ocr': Object.freeze({ en:'Image to Text OCR', ar:'استخراج النص من الصور OCR', es:'OCR de imagen a texto', fr:'OCR d’image vers texte', de:'Bild-zu-Text-OCR', hi:'इमेज OCR से टेक्स्ट', id:'OCR Gambar ke Teks', it:'OCR da immagine a testo', ja:'画像OCR文字認識', ko:'이미지 OCR 텍스트 변환', ms:'OCR Imej kepada Teks', nl:'Afbeelding naar tekst OCR', pl:'OCR obrazu na tekst', pt:'OCR de Imagem para Texto', ru:'Распознавание текста на изображении', sv:'Bild till text OCR', th:'OCR รูปภาพเป็นข้อความ', tr:'Görsel OCR metin çıkarma', uk:'OCR зображення в текст', vi:'OCR ảnh sang văn bản' }),
  'background-blur': Object.freeze({ en:'Background Blur', ar:'تمويه خلفية الصورة', es:'Desenfoque de fondo', fr:'Flou d’arrière-plan', de:'Hintergrund weichzeichnen', hi:'बैकग्राउंड ब्लर', id:'Buram Latar Belakang', it:'Sfocatura dello sfondo', ja:'背景ぼかし', ko:'배경 흐림', ms:'Kabur Latar Belakang', nl:'Achtergrond vervagen', pl:'Rozmycie tła', pt:'Desfoque de Fundo', ru:'Размытие фона', sv:'Bakgrundsoskärpa', th:'เบลอพื้นหลัง', tr:'Arka plan bulanıklaştırma', uk:'Розмиття фону', vi:'Làm mờ nền' }),
  'passport-photo-maker': Object.freeze({ en:'Passport Photo Maker', ar:'صانع صور جواز السفر', es:'Creador de fotos para pasaporte', fr:'Créateur de photos d’identité', de:'Passfoto-Ersteller', hi:'पासपोर्ट फोटो मेकर', id:'Pembuat Foto Paspor', it:'Creatore di foto per passaporto', ja:'パスポート写真メーカー', ko:'여권 사진 만들기', ms:'Pembuat Foto Pasport', nl:'Pasfoto maker', pl:'Kreator zdjęć paszportowych', pt:'Criador de Fotos para Passaporte', ru:'Создатель фото на паспорт', sv:'Passfotoverktyg', th:'สร้างรูปถ่ายหนังสือเดินทาง', tr:'Pasaport fotoğrafı oluşturucu', uk:'Створювач фото на паспорт', vi:'Tạo ảnh hộ chiếu' }),
  'watermark-adder': Object.freeze({ en:'Watermark Adder', ar:'إضافة علامة مائية', es:'Añadir marca de agua', fr:'Ajouter un filigrane', de:'Wasserzeichen hinzufügen', hi:'वॉटरमार्क जोड़ें', id:'Penambah Tanda Air', it:'Aggiungi filigrana', ja:'透かし追加', ko:'워터마크 추가', ms:'Penambah Tanda Air', nl:'Watermerk toevoegen', pl:'Dodawanie znaku wodnego', pt:'Adicionar Marca d’água', ru:'Добавление водяного знака', sv:'Lägg till vattenstämpel', th:'เพิ่มลายน้ำ', tr:'Filigran ekleme', uk:'Додавання водяних знаків', vi:'Thêm hình mờ' }),
  'meme-generator': Object.freeze({ en:'Meme Generator', ar:'منشئ الميمات', es:'Generador de memes', fr:'Générateur de mèmes', de:'Meme-Generator', hi:'मीम जनरेटर', id:'Generator Meme', it:'Generatore di meme', ja:'ミームジェネレーター', ko:'밈 생성기', ms:'Penjana Meme', nl:'Memegenerator', pl:'Generator memów', pt:'Gerador de Memes', ru:'Генератор мемов', sv:'Memgenerator', th:'เครื่องมือสร้างมีม', tr:'Meme oluşturucu', uk:'Генератор мемів', vi:'Trình tạo meme' }),
  'collage-maker': Object.freeze({ en:'Collage Maker', ar:'منشئ الكولاج', es:'Creador de collages', fr:'Créateur de collages', de:'Collage-Ersteller', hi:'कोलाज मेकर', id:'Pembuat Kolase', it:'Creatore di collage', ja:'コラージュ作成', ko:'콜라주 만들기', ms:'Pembuat Kolaj', nl:'Collagemaker', pl:'Kreator kolaży', pt:'Criador de Colagens', ru:'Создатель коллажей', sv:'Kollageverktyg', th:'เครื่องมือสร้างภาพคอลลาจ', tr:'Kolaj oluşturucu', uk:'Створювач колажів', vi:'Trình tạo ảnh ghép' }),
  'image-effects': Object.freeze({ en:'Image Effects', ar:'تأثيرات الصور', es:'Efectos de imagen', fr:'Effets d’image', de:'Bildeffekte', hi:'इमेज इफेक्ट्स', id:'Efek Gambar', it:'Effetti immagine', ja:'画像エフェクト', ko:'이미지 효과', ms:'Kesan Imej', nl:'Afbeeldingseffecten', pl:'Efekty obrazów', pt:'Efeitos de Imagem', ru:'Эффекты изображения', sv:'Bildeffekter', th:'เอฟเฟกต์รูปภาพ', tr:'Görsel efektleri', uk:'Ефекти зображень', vi:'Hiệu ứng ảnh' }),
  'exif-cleaner': Object.freeze({ en:'EXIF Metadata Remover', ar:'إزالة بيانات EXIF', es:'Eliminador de metadatos EXIF', fr:'Suppression des métadonnées EXIF', de:'EXIF-Metadaten entfernen', hi:'EXIF मेटाडेटा रिमूवर', id:'Penghapus Metadata EXIF', it:'Rimozione metadati EXIF', ja:'EXIFメタデータ削除', ko:'EXIF 메타데이터 제거', ms:'Pembersih Metadata EXIF', nl:'EXIF-metadata verwijderen', pl:'Usuwanie metadanych EXIF', pt:'Removedor de Metadados EXIF', ru:'Удаление EXIF-метаданных', sv:'Ta bort EXIF-metadata', th:'ลบข้อมูลเมตา EXIF', tr:'EXIF meta verilerini kaldırma', uk:'Очищення метаданих EXIF', vi:'Xóa siêu dữ liệu EXIF' }),
  'svg-optimizer': Object.freeze({ en:'SVG Optimizer', ar:'تحسين ملفات SVG', es:'Optimizador SVG', fr:'Optimiseur SVG', de:'SVG-Optimierer', hi:'SVG ऑप्टिमाइज़र', id:'Pengoptimal SVG', it:'Ottimizzatore SVG', ja:'SVG最適化', ko:'SVG 최적화기', ms:'Pengoptimum SVG', nl:'SVG-optimizer', pl:'Optymalizator SVG', pt:'Otimizador SVG', ru:'Оптимизатор SVG', sv:'SVG-optimerare', th:'เครื่องมือเพิ่มประสิทธิภาพ SVG', tr:'SVG iyileştirici', uk:'Оптимізатор SVG', vi:'Trình tối ưu hóa SVG' }),
  'mockup-generator': Object.freeze({ en:'Mockup Generator', ar:'منشئ نماذج العرض', es:'Generador de mockups', fr:'Générateur de mockups', de:'Mockup-Generator', hi:'मॉकअप जनरेटर', id:'Generator Mockup', it:'Generatore di mockup', ja:'モックアップ生成', ko:'목업 생성기', ms:'Penjana Mockup', nl:'Mockupgenerator', pl:'Generator makiet', pt:'Gerador de Mockups', ru:'Генератор мокапов', sv:'Mockupgenerator', th:'เครื่องมือสร้างม็อกอัป', tr:'Mockup oluşturucu', uk:'Генератор мокапів', vi:'Trình tạo mockup' }),
  seed: Object.freeze({ en:'Seed Image Editor', ar:'محرر الصور Seed', es:'Editor de imágenes Seed', fr:'Éditeur d’images Seed', de:'Seed-Bildeditor', hi:'Seed इमेज एडिटर', id:'Editor Imej Seed', it:'Editor immagini Seed', ja:'Seed画像エディター', ko:'Seed 이미지 편집기', ms:'Penyunting Imej Seed', nl:'Seed-afbeeldingseditor', pl:'Edytor obrazów Seed', pt:'Editor de Imagens Seed', ru:'Фоторедактор Seed', sv:'Seed-bildredigerare', th:'เครื่องมือแก้ไขรูปภาพ Seed', tr:'Seed Görsel Düzenleyici', uk:'Редактор зображень Seed', vi:'Trình chỉnh sửa ảnh Seed' }),
  pix: Object.freeze({ en:'Pix Studio', ar:'استوديو Pix', es:'Estudio Pix', fr:'Studio Pix', de:'Pix Studio', hi:'Pix स्टूडियो', id:'Studio Pix', it:'Studio Pix', ja:'Pix スタジオ', ko:'Pix 스튜디오', ms:'Studio Pix', nl:'Pix Studio', pl:'Studio Pix', pt:'Estúdio Pix', ru:'Студия Pix', sv:'Pix Studio', th:'Pix Studio', tr:'Pix Stüdyo', uk:'Студія Pix', vi:'Xưởng Pix' }),
  'ai-image-generator': Object.freeze({ en:'AI Image Generator', ar:'مولد الصور بالذكاء الاصطناعي', es:'Generador de imágenes con IA', fr:'Générateur d’images IA', de:'KI-Bildgenerator', hi:'एआई इमेज जनरेटर', id:'Generator Gambar AI', it:'Generatore di immagini AI', ja:'AI画像生成', ko:'AI 이미지 생성기', ms:'Penjana Imej AI', nl:'AI-afbeeldingsgenerator', pl:'Generator obrazów AI', pt:'Gerador de Imagens com IA', ru:'AI-генератор изображений', sv:'AI-bildgenerator', th:'เครื่องมือสร้างรูปภาพ AI', tr:'Yapay zekâ görsel oluşturucu', uk:'AI-генератор зображень', vi:'Trình tạo ảnh AI' }),
  'photo-colorizer': Object.freeze({ en:'Photo Colorizer', ar:'ملوّن الصور', es:'Colorizador de fotos', fr:'Coloriseur de photos', de:'Fotokolorierer', hi:'फोटो कलराइज़र', id:'Pewarna Foto', it:'Colorizzatore di foto', ja:'写真カラー化', ko:'사진 색상화', ms:'Pewarna Foto', nl:'Foto-kleurgever', pl:'Koloryzator zdjęć', pt:'Colorizador de Fotos', ru:'Колоризатор фотографий', sv:'Fotokoloriserare', th:'เครื่องมือเติมสีภาพถ่าย', tr:'Fotoğraf renklendirici', uk:'Колоризатор фотографій', vi:'Trình tô màu ảnh' }),
  'video-trimmer': Object.freeze({ en:'Video Trimmer', ar:'قص الفيديو', es:'Recortador de video', fr:'Rognage vidéo', de:'Video-Trimmer', hi:'वीडियो ट्रिमर', id:'Pemotong Video', it:'Taglia video', ja:'動画トリマー', ko:'비디오 트리머', ms:'Pemotong Video', nl:'Videotrimmer', pl:'Przycinanie wideo', pt:'Cortador de Vídeo', ru:'Обрезка видео', sv:'Videoklippare', th:'เครื่องมือตัดวิดีโอ', tr:'Video kırpıcı', uk:'Обрізка відео', vi:'Trình cắt video' }),
  'video-cropper': Object.freeze({ en:'Video Cropper', ar:'قص أطراف الفيديو', es:'Recortador de video', fr:'Recadrage vidéo', de:'Video-Zuschneiden', hi:'वीडियो क्रॉपर', id:'Pemotong Bingkai Video', it:'Ritaglio video', ja:'動画クロッパー', ko:'비디오 자르기', ms:'Pemotong Video', nl:'Video bijsnijden', pl:'Kadrowanie wideo', pt:'Corte de Vídeo', ru:'Кадрирование видео', sv:'Beskär video', th:'เครื่องมือครอบตัดวิดีโอ', tr:'Video kırpma', uk:'Обрізання відео', vi:'Cắt video' }),
  'video-resizer': Object.freeze({ en:'Video Resizer', ar:'تغيير حجم الفيديو', es:'Redimensionador de video', fr:'Redimensionneur vidéo', de:'Video-Größenänderung', hi:'वीडियो रिसाइज़र', id:'Pengubah Ukuran Video', it:'Ridimensiona video', ja:'動画リサイズ', ko:'비디오 크기 조정', ms:'Pengubah Saiz Video', nl:'Videoformaat wijzigen', pl:'Zmiana rozmiaru wideo', pt:'Redimensionador de Vídeo', ru:'Изменение размера видео', sv:'Ändra storlek på video', th:'เครื่องมือปรับขนาดวิดีโอ', tr:'Video yeniden boyutlandırıcı', uk:'Зміна розміру відео', vi:'Đổi kích thước video' }),
  'video-compressor': Object.freeze({ en:'Video Compressor', ar:'ضغط الفيديو', es:'Compresor de video', fr:'Compresseur vidéo', de:'Videokompressor', hi:'वीडियो कंप्रेसर', id:'Kompresor Video', it:'Compressore video', ja:'動画圧縮', ko:'비디오 압축기', ms:'Pemampat Video', nl:'Videocompressor', pl:'Kompresor wideo', pt:'Compressor de Vídeo', ru:'Сжатие видео', sv:'Videokompressor', th:'เครื่องมือบีบอัดวิดีโอ', tr:'Video sıkıştırıcı', uk:'Компресор відео', vi:'Trình nén video' }),
  'image-rotate': Object.freeze({ en:'Rotate Image', ar:'تدوير الصور', es:'Rotar imagen', fr:'Faire pivoter l’image', de:'Bild drehen', hi:'इमेज घुमाएँ', id:'Putar Gambar', it:'Ruota immagine', ja:'画像を回転', ko:'이미지 회전', ms:'Putar Imej', nl:'Afbeelding draaien', pl:'Obracanie obrazu', pt:'Girar Imagem', ru:'Поворот изображения', sv:'Rotera bild', th:'หมุนรูปภาพ', tr:'Görsel döndürme', uk:'Поворот зображення', vi:'Xoay ảnh' }),
  'image-flip-horizontal': Object.freeze({ en:'Flip Image Horizontal', ar:'قلب الصورة أفقيًا', es:'Voltear imagen horizontalmente', fr:'Retourner l’image horizontalement', de:'Bild horizontal spiegeln', hi:'इमेज क्षैतिज पलटें', id:'Balik Gambar Horizontal', it:'Capovolgi immagine orizzontalmente', ja:'画像を水平反転', ko:'이미지 가로 뒤집기', ms:'Balik Imej Mendatar', nl:'Afbeelding horizontaal spiegelen', pl:'Poziome odbicie obrazu', pt:'Inverter Imagem Horizontalmente', ru:'Горизонтальное отражение изображения', sv:'Vänd bild horisontellt', th:'กลับภาพแนวนอน', tr:'Görseli yatay çevirme', uk:'Горизонтальне віддзеркалення', vi:'Lật ảnh ngang' }),
  'image-flip-vertical': Object.freeze({ en:'Flip Image Vertical', ar:'قلب الصورة رأسيًا', es:'Voltear imagen verticalmente', fr:'Retourner l’image verticalement', de:'Bild vertikal spiegeln', hi:'इमेज लंबवत पलटें', id:'Balik Gambar Vertikal', it:'Capovolgi immagine verticalmente', ja:'画像を垂直反転', ko:'이미지 세로 뒤집기', ms:'Balik Imej Menegak', nl:'Afbeelding verticaal spiegelen', pl:'Pionowe odbicie obrazu', pt:'Inverter Imagem Verticalmente', ru:'Вертикальное отражение изображения', sv:'Vänd bild vertikalt', th:'กลับภาพแนวตั้ง', tr:'Görseli dikey çevirme', uk:'Вертикальне віддзеркалення', vi:'Lật ảnh dọc' }),
  'image-brightness': Object.freeze({ en:'Brightness', ar:'سطوع الصورة', es:'Brillo de imagen', fr:'Luminosité de l’image', de:'Bildhelligkeit', hi:'इमेज चमक', id:'Kecerahan Gambar', it:'Luminosità immagine', ja:'画像の明るさ', ko:'이미지 밝기', ms:'Kecerahan Imej', nl:'Afbeeldingshelderheid', pl:'Jasność obrazu', pt:'Brilho da Imagem', ru:'Яркость изображения', sv:'Bildljusstyrka', th:'ความสว่างรูปภาพ', tr:'Görsel parlaklığı', uk:'Яскравість зображення', vi:'Độ sáng ảnh' }),
  'image-contrast': Object.freeze({ en:'Image Contrast', ar:'تباين الصورة', es:'Contraste de imagen', fr:'Contraste de l’image', de:'Bildkontrast', hi:'इमेज कंट्रास्ट', id:'Kontras Gambar', it:'Contrasto immagine', ja:'画像のコントラスト', ko:'이미지 대비', ms:'Kontras Imej', nl:'Afbeeldingscontrast', pl:'Kontrast obrazu', pt:'Contraste da Imagem', ru:'Контраст изображения', sv:'Bildkontrast', th:'คอนทราสต์รูปภาพ', tr:'Görsel kontrastı', uk:'Контраст зображення', vi:'Độ tương phản ảnh' }),
  'image-saturation': Object.freeze({ en:'Image Saturation', ar:'تشبع الصورة', es:'Saturación de imagen', fr:'Saturation de l’image', de:'Bildsättigung', hi:'इमेज सैचुरेशन', id:'Saturasi Gambar', it:'Saturazione immagine', ja:'画像の彩度', ko:'이미지 채도', ms:'Ketepuan Imej', nl:'Afbeeldingsverzadiging', pl:'Nasycenie obrazu', pt:'Saturação da Imagem', ru:'Насыщенность изображения', sv:'Bildmättnad', th:'ความอิ่มตัวของสี', tr:'Görsel doygunluğu', uk:'Насиченість зображення', vi:'Độ bão hòa ảnh' }),
  'image-grayscale': Object.freeze({ en:'Grayscale Image', ar:'تدرج رمادي للصورة', es:'Imagen en escala de grises', fr:'Image en niveaux de gris', de:'Graustufenbild', hi:'ग्रेस्केल इमेज', id:'Gambar Skala Kelabu', it:'Immagine in scala di grigi', ja:'グレースケール画像', ko:'그레이스케일 이미지', ms:'Imej Skala Kelabu', nl:'Grijswaardenafbeelding', pl:'Obraz w skali szarości', pt:'Imagem em Tons de Cinza', ru:'Изображение в градациях серого', sv:'Gråskalebild', th:'ภาพระดับสีเทา', tr:'Gri tonlamalı görsel', uk:'Зображення у відтінках сірого', vi:'Ảnh thang độ xám' }),
  'image-invert': Object.freeze({ en:'Invert Image Colors', ar:'عكس ألوان الصورة', es:'Invertir colores de imagen', fr:'Inverser les couleurs de l’image', de:'Bildfarben invertieren', hi:'इमेज रंग उलटें', id:'Balik Warna Gambar', it:'Inverti colori immagine', ja:'画像の色を反転', ko:'이미지 색상 반전', ms:'Songsangkan Warna Imej', nl:'Afbeeldingskleuren inverteren', pl:'Odwracanie kolorów obrazu', pt:'Inverter Cores da Imagem', ru:'Инверсия цветов изображения', sv:'Invertera bildfärger', th:'กลับสีรูปภาพ', tr:'Görsel renklerini tersine çevirme', uk:'Інверсія кольорів зображення', vi:'Đảo màu ảnh' }),
  'image-sepia': Object.freeze({ en:'Sepia Image Effect', ar:'تأثير سيبيا للصورة', es:'Efecto sepia', fr:'Effet sépia', de:'Sepia-Effekt', hi:'सेपिया इमेज इफेक्ट', id:'Kesan Sepia', it:'Effetto seppia', ja:'セピア効果', ko:'세피아 효과', ms:'Kesan Sepia', nl:'Sepia-effect', pl:'Efekt sepii', pt:'Efeito Sépia', ru:'Эффект сепии', sv:'Sepiaeffekt', th:'เอฟเฟกต์ซีเปีย', tr:'Sepya efekti', uk:'Ефект сепії', vi:'Hiệu ứng màu nâu đỏ' }),
  'image-blur': Object.freeze({ en:'Blur Image', ar:'تمويه الصورة', es:'Desenfocar imagen', fr:'Flouter l’image', de:'Bild weichzeichnen', hi:'इमेज धुंधली करें', id:'Kaburkan Gambar', it:'Sfoca immagine', ja:'画像をぼかす', ko:'이미지 흐리게', ms:'Kaburkan Imej', nl:'Afbeelding vervagen', pl:'Rozmycie obrazu', pt:'Desfocar Imagem', ru:'Размытие изображения', sv:'Görseli bulanıklaştır', th:'เบลอรูปภาพ', tr:'Görsel bulanıklaştırma', uk:'Розмиття зображення', vi:'Làm mờ ảnh' }),
  'image-sharpen': Object.freeze({ en:'Sharpen Image', ar:'زيادة حدة الصورة', es:'Enfocar imagen', fr:'Accentuer l’image', de:'Bild schärfen', hi:'इमेज शार्प करें', id:'Tajamkan Gambar', it:'Nitidezza immagine', ja:'画像をシャープに', ko:'이미지 선명하게', ms:'Menajamkan Imej', nl:'Afbeelding verscherpen', pl:'Wyostrzanie obrazu', pt:'Aumentar Nitidez da Imagem', ru:'Повышение резкости изображения', sv:'Skärpa bild', th:'เพิ่มความคมชัดรูปภาพ', tr:'Görsel keskinleştirme', uk:'Підвищення різкості зображення', vi:'Làm sắc nét ảnh' }),
  'image-resizer': Object.freeze({ en:'Resize Image', ar:'تغيير حجم الصورة', es:'Redimensionar imagen', fr:'Redimensionner l’image', de:'Bildgröße ändern', hi:'इमेज का आकार बदलें', id:'Ubah Ukuran Gambar', it:'Ridimensiona immagine', ja:'画像サイズ変更', ko:'이미지 크기 조정', ms:'Ubah Saiz Imej', nl:'Afbeelding verkleinen', pl:'Zmiana rozmiaru obrazu', pt:'Redimensionar Imagem', ru:'Изменение размера изображения', sv:'Ändra bildstorlek', th:'ปรับขนาดรูปภาพ', tr:'Görseli yeniden boyutlandır', uk:'Зміна розміру зображення', vi:'Thay đổi kích thước ảnh' }),
  'image-hue': Object.freeze({ en:'Hue', ar:'درجة لون الصورة', es:'Tono de imagen', fr:'Teinte de l’image', de:'Bildfarbton', hi:'इमेज ह्यू', id:'Rona Gambar', it:'Tonalità immagine', ja:'画像の色相', ko:'이미지 색조', ms:'Rona Imej', nl:'Afbeeldingstint', pl:'Barwa obrazu', pt:'Matiz da Imagem', ru:'Цветовой тон изображения', sv:'Bildens nyans', th:'เฉดสีรูปภาพ', tr:'Görsel tonu', uk:'Відтінок зображення', vi:'Sắc độ ảnh' }),
  'image-pixelate': Object.freeze({ en:'Pixelate Image', ar:'بكسلة الصورة', es:'Pixelar imagen', fr:'Pixelliser l’image', de:'Bild pixeln', hi:'इमेज पिक्सेलेट करें', id:'Pikselkan Gambar', it:'Pixelizza immagine', ja:'画像をピクセル化', ko:'이미지 픽셀화', ms:'Pikselkan Imej', nl:'Afbeelding pixeleren', pl:'Pikselizacja obrazu', pt:'Pixelizar Imagem', ru:'Пикселизация изображения', sv:'Pixelera bild', th:'ทำภาพพิกเซล', tr:'Görseli pikselleştir', uk:'Пікселізація зображення', vi:'Pixel hóa ảnh' }),
  'image-padding': Object.freeze({ en:'Image Padding', ar:'هوامش الصورة', es:'Margen de imagen', fr:'Marge de l’image', de:'Bildinnenabstand', hi:'इमेज पैडिंग', id:'Padding Gambar', it:'Bordo immagine', ja:'画像パディング', ko:'이미지 여백', ms:'Jidar Imej', nl:'Afbeeldingsmarge', pl:'Margines obrazu', pt:'Margem da Imagem', ru:'Поля изображения', sv:'Bildmarginal', th:'ขอบรูปภาพ', tr:'Görsel dolgusu', uk:'Відступи зображення', vi:'Khoảng đệm ảnh' }),
  'image-rounded-corners': Object.freeze({ en:'Rounded Corners', ar:'زوايا مستديرة', es:'Esquinas redondeadas', fr:'Coins arrondis', de:'Abgerundete Ecken', hi:'गोल कोने', id:'Sudut Membulat', it:'Angoli arrotondati', ja:'角を丸くする', ko:'둥근 모서리', ms:'Sudut Bulat', nl:'Afgeronde hoeken', pl:'Zaokrąglone rogi', pt:'Cantos Arredondados', ru:'Скруглённые углы', sv:'Rundade hörn', th:'มุมโค้งมน', tr:'Yuvarlatılmış köşeler', uk:'Заокруглені кути', vi:'Bo góc tròn' }),
  ...NEW_CANONICAL_IMAGE_SEO_NAMES,
});

export function getToolSeoName(toolId: string, locale: Locale): string | undefined {
  return TOOL_SEO_NAMES[toolId]?.[locale];
}
